/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Configuration of the announcement banner.
 *
 * @param isDismissible, optional, Flag indicating if the announcement banner can be dismissed by the user.
 * @param isEnabled, optional, Flag indicating if the announcement banner is enabled or not.
 * @param message, optional, The text on the announcement banner.
 * @param visibility, optional, Visibility of the announcement banner. Can be public or private.
 */
@Serializable
data class AnnouncementBannerConfigurationUpdate(
    @SerialName("isDismissible") val isDismissible: Boolean? = null,
    @SerialName("isEnabled") val isEnabled: Boolean? = null,
    @SerialName("message") val message: String? = null,
    @SerialName("visibility") val visibility: String? = null
)