/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of an application role.
 *
 * @param defaultGroups, optional, The groups that are granted default access for this application role. As a group's name can change, use of `defaultGroupsDetails` is recommended to identify a groups.
 * @param defaultGroupsDetails, optional, The groups that are granted default access for this application role.
 * @param defined, optional, Deprecated.
 * @param groupDetails, optional, The groups associated with the application role.
 * @param groups, optional, The groups associated with the application role. As a group's name can change, use of `groupDetails` is recommended to identify a groups.
 * @param hasUnlimitedSeats, optional
 * @param key, optional, The key of the application role.
 * @param name, optional, The display name of the application role.
 * @param numberOfSeats, optional, The maximum count of users on your license.
 * @param platform, optional, Indicates if the application role belongs to Jira platform (`jira-core`).
 * @param remainingSeats, optional, The count of users remaining on your license.
 * @param selectedByDefault, optional, Determines whether this application role should be selected by default on user creation.
 * @param userCount, optional, The number of users counting against your license.
 * @param userCountDescription, optional, The [type of users](https://confluence.atlassian.com/x/lRW3Ng) being counted against your license.
 */
@Serializable
data class ApplicationRole(
    @SerialName("defaultGroups") val defaultGroups: List<String>? = null,
    @SerialName("defaultGroupsDetails") val defaultGroupsDetails: List<GroupName>? = null,
    @SerialName("defined") val defined: Boolean? = null,
    @SerialName("groupDetails") val groupDetails: List<GroupName>? = null,
    @SerialName("groups") val groups: List<String>? = null,
    @SerialName("hasUnlimitedSeats") val hasUnlimitedSeats: Boolean? = null,
    @SerialName("key") val key: String? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("numberOfSeats") val numberOfSeats: Int? = null,
    @SerialName("platform") val platform: Boolean? = null,
    @SerialName("remainingSeats") val remainingSeats: Int? = null,
    @SerialName("selectedByDefault") val selectedByDefault: Boolean? = null,
    @SerialName("userCount") val userCount: Int? = null,
    @SerialName("userCountDescription") val userCountDescription: String? = null
)