/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * A workflow transition rule.
 *
 * @param ruleConfiguration, optional, A rule configuration.
 * @param id, required, The ID of the transition rule.
 * @param key, required, The key of the rule, as defined in the Connect or the Forge app descriptor.
 * @param transition, optional
 */
@Serializable
data class AppWorkflowTransitionRule(
    @SerialName("ruleConfiguration") val ruleConfiguration: RuleConfiguration? = null,
    @SerialName("id") val id: String,
    @SerialName("key") val key: String,
    @SerialName("transition") val transition: transition? = null
)