/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of an item associated with the changed record.
 *
 * @param id, optional, The ID of the associated record.
 * @param name, optional, The name of the associated record.
 * @param parentId, optional, The ID of the associated parent record.
 * @param parentName, optional, The name of the associated parent record.
 * @param typeName, optional, The type of the associated record.
 */
@Serializable
data class AssociatedItemBean(
    @SerialName("id") val id: String? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("parentId") val parentId: String? = null,
    @SerialName("parentName") val parentName: String? = null,
    @SerialName("typeName") val typeName: String? = null
)