/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details about an attachment.
 *
 * @param author, optional, Details of the user who added the attachment.
 * @param content, optional, The content of the attachment.
 * @param created, optional, The datetime the attachment was created.
 * @param filename, optional, The file name of the attachment.
 * @param id, optional, The ID of the attachment.
 * @param mimeType, optional, The MIME type of the attachment.
 * @param self, optional, The URL of the attachment details response.
 * @param size, optional, The size of the attachment.
 * @param thumbnail, optional, The URL of a thumbnail representing the attachment.
 */
@Serializable
data class Attachment(
    @SerialName("author") val author: UserDetails? = null,
    @SerialName("content") val content: String? = null,
    @SerialName("created") val created: String? = null,
    @SerialName("filename") val filename: String? = null,
    @SerialName("id") val id: String? = null,
    @SerialName("mimeType") val mimeType: String? = null,
    @SerialName("self") val self: String? = null,
    @SerialName("size") val size: Long? = null,
    @SerialName("thumbnail") val thumbnail: String? = null
)