/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param entries, optional, The list of the items included in the archive.
 * @param totalEntryCount, optional, The number of items in the archive.
 */
@Serializable
data class AttachmentArchiveImpl(
    @SerialName("entries") val entries: List<AttachmentArchiveEntry>? = null,
    @SerialName("totalEntryCount") val totalEntryCount: Int? = null
)