/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Container for a list of audit records.
 *
 * @param limit, optional, The requested or default limit on the number of audit items to be returned.
 * @param offset, optional, The number of audit items skipped before the first item in this list.
 * @param records, optional, The list of audit items.
 * @param total, optional, The total number of audit items returned.
 */
@Serializable
data class AuditRecords(
    @SerialName("limit") val limit: Int? = null,
    @SerialName("offset") val offset: Int? = null,
    @SerialName("records") val records: List<AuditRecordBean>? = null,
    @SerialName("total") val total: Long? = null
)