/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The Atlassian provided system rules available.
 *
 * @param description, required, The rule description.
 * @param incompatibleRuleKeys, required, List of rules that conflict with this one.
 * @param isAvailableForInitialTransition, required, Whether the rule can be added added to an initial transition.
 * @param isVisible, required, Whether the rule is visible.
 * @param name, required, The rule name.
 * @param ruleKey, required, The rule key.
 * @param ruleType, required, The rule type.
 */
@Serializable
data class AvailableWorkflowSystemRule(
    @SerialName("description") val description: String,
    @SerialName("incompatibleRuleKeys") val incompatibleRuleKeys: List<String>,
    @SerialName("isAvailableForInitialTransition") val isAvailableForInitialTransition: Boolean,
    @SerialName("isVisible") val isVisible: Boolean,
    @SerialName("name") val name: String,
    @SerialName("ruleKey") val ruleKey: String,
    @SerialName("ruleType") val ruleType: String
)