/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param errorCollection, optional, Error messages from an operation.
 * @param failedElementNumber, optional
 * @param status, optional
 */
@Serializable
data class BulkOperationErrorResult(
    @SerialName("errorCollection") val errorCollection: ErrorCollection? = null,
    @SerialName("failedElementNumber") val failedElementNumber: Int? = null,
    @SerialName("status") val status: Int? = null
)