/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The list of requested issues & fields.
 *
 * @param issueErrors, optional, When Jira can't return an issue enumerated in a request due to a retriable error or payload constraint, we'll return the respective issue ID with a corresponding error message. This list is empty when there are no errors Issues which aren't found or that the user doesn't have permission to view won't be returned in this list.
 * @param issues, optional, The list of issues.
 */
@Serializable
data class BulkIssueResults(
    @SerialName("issueErrors") val issueErrors: List<IssueError>? = null,
    @SerialName("issues") val issues: List<IssueBean>? = null
)