/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Errors of bulk edit action.
 *
 * @param errorMessages, required, The error messages.
 * @param errors, required, The errors.
 */
@Serializable
data class BulkEditActionError(
    @SerialName("errorMessages") val errorMessages: List<String>,
    @SerialName("errors") val errors: errors
)