/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Bulk Edit Get Fields Response.
 *
 * @param endingBefore, optional, The end cursor for use in pagination.
 * @param fields, optional, List of all the fields
 * @param startingAfter, optional, The start cursor for use in pagination.
 */
@Serializable
data class BulkEditGetFields(
    @SerialName("endingBefore") val endingBefore: String? = null,
    @SerialName("fields") val fields: List<IssueBulkEditField>? = null,
    @SerialName("startingAfter") val startingAfter: String? = null
)