/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details of a request to bulk edit shareable entity.
 *
 * @param action, required, Allowed action for bulk edit shareable entity
 * @param entityErrors, optional, The mapping dashboard id to errors if any.
 */
@Serializable
data class BulkEditShareableEntityResponse(
    @SerialName("action") val action: String,
    @SerialName("entityErrors") val entityErrors: entityErrors? = null
)