/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of the contextual configuration for a custom field.
 *
 * @param configuration, optional, The field configuration.
 * @param customFieldId, required, The ID of the custom field.
 * @param fieldContextId, required, The ID of the field context the configuration is associated with.
 * @param id, required, The ID of the configuration.
 * @param schema, optional, The field value schema.
 */
@Serializable
data class BulkContextualConfiguration(
    @SerialName("configuration") val configuration: String? = null,
    @SerialName("customFieldId") val customFieldId: String,
    @SerialName("fieldContextId") val fieldContextId: String,
    @SerialName("id") val id: String,
    @SerialName("schema") val schema: String? = null
)