/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * A container for the watch status of a list of issues.
 *
 * @param issuesIsWatching, optional, The map of issue ID to boolean watch status.
 */
@Serializable
data class BulkIssueIsWatching(
    @SerialName("issuesIsWatching") val issuesIsWatching: issuesIsWatching? = null
)