/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A page of changelogs which is designed to handle multiple issues
 *
 * @param issueChangeLogs, optional, The list of issues changelogs.
 * @param nextPageToken, optional, Continuation token to fetch the next page. If this result represents the last or the only page, this token will be null.
 */
@Serializable
data class BulkChangelogResponseBean(
    @SerialName("issueChangeLogs") val issueChangeLogs: List<IssueChangeLog>? = null,
    @SerialName("nextPageToken") val nextPageToken: String? = null
)