/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Request bean for bulk changelog retrieval
 *
 * @param fieldIds, optional, List of field IDs to filter changelogs
 * @param issueIdsOrKeys, required, List of issue IDs/keys to fetch changelogs for
 * @param maxResults, optional, The maximum number of items to return per page
 * @param nextPageToken, optional, The cursor for pagination
 */
@Serializable
data class BulkChangelogRequestBean(
    @SerialName("fieldIds") val fieldIds: List<String>? = null,
    @SerialName("issueIdsOrKeys") val issueIdsOrKeys: List<String>,
    @SerialName("maxResults") val maxResults: Int = 1000,
    @SerialName("nextPageToken") val nextPageToken: String? = null
)