/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of global permissions to look up and project permissions with associated projects and issues to look up.
 *
 * @param accountId, optional, The account ID of a user.
 * @param globalPermissions, optional, Global permissions to look up.
 * @param projectPermissions, optional, Project permissions with associated projects and issues to look up.
 */
@Serializable
data class BulkPermissionsRequestBean(
    @SerialName("accountId") val accountId: String? = null,
    @SerialName("globalPermissions") val globalPermissions: List<String>? = null,
    @SerialName("projectPermissions") val projectPermissions: List<BulkProjectPermissions>? = null
)