/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Bulk issue property update request details.
 *
 * @param expression, optional, EXPERIMENTAL. The Jira expression to calculate the value of the property. The value of the expression must be an object that can be converted to JSON, such as a number, boolean, string, list, or map. The context variables available to the expression are `issue` and `user`. Issues for which the expression returns a value whose JSON representation is longer than 32768 characters are ignored.
 * @param filter, optional, The bulk operation filter.
 * @param value, optional, The value of the property. The value must be a [valid](https://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.
 */
@Serializable
data class BulkIssuePropertyUpdateRequest(
    @SerialName("expression") val expression: String? = null,
    @SerialName("filter") val filter: IssueFilterForBulkPropertySet? = null,
    @SerialName("value") val value: String? = null
)