/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param expand, optional, Use [expand](#expansion) to include additional information about issues in the response. Note that, unlike the majority of instances where `expand` is specified, `expand` is defined as a list of values. The expand options are:

 *  `renderedFields` Returns field values rendered in HTML format.
 *  `names` Returns the display name of each field.
 *  `schema` Returns the schema describing a field type.
 *  `transitions` Returns all possible transitions for the issue.
 *  `operations` Returns all possible operations for the issue.
 *  `editmeta` Returns information about how each field can be edited.
 *  `changelog` Returns a list of recent updates to an issue, sorted by date, starting from the most recent.
 *  `versionedRepresentations` Instead of `fields`, returns `versionedRepresentations` a JSON array containing each version of a field's value, with the highest numbered item representing the most recent version.
 * @param fields, optional, A list of fields to return for each issue, use it to retrieve a subset of fields. This parameter accepts a comma-separated list. Expand options include:

 *  `*all` Returns all fields.
 *  `*navigable` Returns navigable fields.
 *  Any issue field, prefixed with a minus to exclude.

The default is `*navigable`.

Examples:

 *  `summary,comment` Returns the summary and comments fields only.
 *  `-description` Returns all navigable (default) fields except description.
 *  `*all,-comment` Returns all fields except comments.

Multiple `fields` parameters can be included in a request.

Note: All navigable fields are returned by default. This differs from [GET issue](#api-rest-api-3-issue-issueIdOrKey-get) where the default is all fields.
 * @param fieldsByKeys, optional, Reference fields by their key (rather than ID). The default is `false`.
 * @param issueIdsOrKeys, required, An array of issue IDs or issue keys to fetch. You can mix issue IDs and keys in the same query.
 * @param properties, optional, A list of issue property keys of issue properties to be included in the results. A maximum of 5 issue property keys can be specified.
 */
@Serializable
data class BulkFetchIssueRequestBean(
    @SerialName("expand") val expand: List<String>? = null,
    @SerialName("fields") val fields: List<String>? = null,
    @SerialName("fieldsByKeys") val fieldsByKeys: Boolean? = null,
    @SerialName("issueIdsOrKeys") val issueIdsOrKeys: List<String>,
    @SerialName("properties") val properties: List<String>? = null
)