/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of names changed in the record event.
 *
 * @param changedFrom, optional, The value of the field before the change.
 * @param changedTo, optional, The value of the field after the change.
 * @param fieldName, optional, The name of the field changed.
 */
@Serializable
data class ChangedValueBean(
    @SerialName("changedFrom") val changedFrom: String? = null,
    @SerialName("changedTo") val changedTo: String? = null,
    @SerialName("fieldName") val fieldName: String? = null
)