/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A change item.
 *
 * @param field, optional, The name of the field changed.
 * @param fieldId, optional, The ID of the field changed.
 * @param fieldtype, optional, The type of the field changed.
 * @param from, optional, The details of the original value.
 * @param fromString, optional, The details of the original value as a string.
 * @param to, optional, The details of the new value.
 * @param toString, optional, The details of the new value as a string.
 */
@Serializable
data class ChangeDetails(
    @SerialName("field") val field: String? = null,
    @SerialName("fieldId") val fieldId: String? = null,
    @SerialName("fieldtype") val fieldtype: String? = null,
    @SerialName("from") val from: String? = null,
    @SerialName("fromString") val fromString: String? = null,
    @SerialName("to") val to: String? = null,
    @SerialName("toString") val toString: String? = null
)