/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Container for a list of registered webhooks. Webhook details are returned in the same order as the request.
 *
 * @param webhookRegistrationResult, optional, A list of registered webhooks.
 */
@Serializable
data class ContainerForRegisteredWebhooks(
    @SerialName("webhookRegistrationResult") val webhookRegistrationResult: List<RegisteredWebhook>? = null
)