/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * A workflow transition condition.
 *
 * @param conditions, optional, The list of workflow conditions.
 * @param configuration, optional, EXPERIMENTAL. The configuration of the transition rule.
 * @param operator, optional, The compound condition operator.
 * @param type, optional, The type of the transition rule.
 */
@Serializable
data class CreateWorkflowCondition(
    @SerialName("conditions") val conditions: List<CreateWorkflowCondition>? = null,
    @SerialName("configuration") val configuration: configuration? = null,
    @SerialName("operator") val operator: String? = null,
    @SerialName("type") val type: String? = null
)