/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of an notification scheme.
 *
 * @param description, optional, The description of the notification scheme.
 * @param name, required, The name of the notification scheme. Must be unique (case-insensitive).
 * @param notificationSchemeEvents, optional, The list of notifications which should be added to the notification scheme.
 */
@Serializable
data class CreateNotificationSchemeDetails(
    @SerialName("description") val description: String? = null,
    @SerialName("name") val name: String,
    @SerialName("notificationSchemeEvents") val notificationSchemeEvents: List<NotificationSchemeEventDetails>? = null
)