/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details about a created issue or subtask.
 *
 * @param id, optional, The ID of the created issue or subtask.
 * @param key, optional, The key of the created issue or subtask.
 * @param self, optional, The URL of the created issue or subtask.
 * @param transition, optional, The response code and messages related to any requested transition.
 * @param watchers, optional, The response code and messages related to any requested watchers.
 */
@Serializable
data class CreatedIssue(
    @SerialName("id") val id: String? = null,
    @SerialName("key") val key: String? = null,
    @SerialName("self") val self: String? = null,
    @SerialName("transition") val transition: transition? = null,
    @SerialName("watchers") val watchers: watchers? = null
)