/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Issue security scheme and it's details
 *
 * @param description, optional, The description of the issue security scheme.
 * @param levels, optional, The list of scheme levels which should be added to the security scheme.
 * @param name, required, The name of the issue security scheme. Must be unique (case-insensitive).
 */
@Serializable
data class CreateIssueSecuritySchemeDetails(
    @SerialName("description") val description: String? = null,
    @SerialName("levels") val levels: List<SecuritySchemeLevelBean>? = null,
    @SerialName("name") val name: String
)