/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of an issue priority.
 *
 * @param avatarId, optional, The ID for the avatar for the priority. Either the iconUrl or avatarId must be defined, but not both. This parameter is nullable and will become mandatory once the iconUrl parameter is deprecated.
 * @param description, optional, The description of the priority.
 * @param iconUrl, optional, The URL of an icon for the priority. Accepted protocols are HTTP and HTTPS. Built in icons can also be used. Either the iconUrl or avatarId must be defined, but not both.
 * @param name, required, The name of the priority. Must be unique.
 * @param statusColor, required, The status color of the priority in 3-digit or 6-digit hexadecimal format.
 */
@Serializable
data class CreatePriorityDetails(
    @SerialName("avatarId") val avatarId: Long? = null,
    @SerialName("description") val description: String? = null,
    @SerialName("iconUrl") val iconUrl: String? = null,
    @SerialName("name") val name: String,
    @SerialName("statusColor") val statusColor: String
)