/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 *
 * @param crossProjectReleases, optional, The cross-project releases to include in the plan.
 * @param customFields, optional, The custom fields for the plan.
 * @param exclusionRules, optional, The exclusion rules for the plan.
 * @param issueSources, required, The issue sources to include in the plan.
 * @param leadAccountId, optional, The account ID of the plan lead.
 * @param name, required, The plan name.
 * @param permissions, optional, The permissions for the plan.
 * @param scheduling, required, The scheduling settings for the plan.
 */
@Serializable
data class CreatePlanRequest(
    @SerialName("crossProjectReleases") val crossProjectReleases: List<CreateCrossProjectReleaseRequest>? = null,
    @SerialName("customFields") val customFields: List<CreateCustomFieldRequest>? = null,
    @SerialName("exclusionRules") val exclusionRules: exclusionRules? = null,
    @SerialName("issueSources") val issueSources: List<CreateIssueSourceRequest>,
    @SerialName("leadAccountId") val leadAccountId: String? = null,
    @SerialName("name") val name: String,
    @SerialName("permissions") val permissions: List<CreatePermissionRequest>? = null,
    @SerialName("scheduling") val scheduling: scheduling
)