/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a custom field context.
 *
 * @param description, optional, The description of the custom field context. The maximum length is 255 characters.
 * @param name, optional, The name of the custom field context. The name must be unique. The maximum length is 255 characters.
 */
@Serializable
data class CustomFieldContextUpdateDetails(
    @SerialName("description") val description: String? = null,
    @SerialName("name") val name: String? = null
)