/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Default value for a Forge number custom field.
 *
 * @param contextId, required, The ID of the context.
 * @param number, required, The default floating-point number.
 * @param type, required
 */
@Serializable
data class CustomFieldContextDefaultValueForgeNumberField(
    @SerialName("contextId") val contextId: String,
    @SerialName("number") val number: Double,
    @SerialName("type") val type: String
)