/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a context to project association.
 *
 * @param contextId, required, The ID of the context.
 * @param isGlobalContext, optional, Whether context is global.
 * @param projectId, optional, The ID of the project.
 */
@Serializable
data class CustomFieldContextProjectMapping(
    @SerialName("contextId") val contextId: String,
    @SerialName("isGlobalContext") val isGlobalContext: Boolean? = null,
    @SerialName("projectId") val projectId: String? = null
)