/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The default value for a single select custom field.
 *
 * @param contextId, required, The ID of the context.
 * @param optionId, required, The ID of the default option.
 * @param type, required
 */
@Serializable
data class CustomFieldContextDefaultValueSingleOption(
    @SerialName("contextId") val contextId: String,
    @SerialName("optionId") val optionId: String,
    @SerialName("type") val type: String
)