/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a custom option for a field.
 *
 * @param self, optional, The URL of these custom field option details.
 * @param value, optional, The value of the custom field option.
 */
@Serializable
data class CustomFieldOption(
    @SerialName("self") val self: String? = null,
    @SerialName("value") val value: String? = null
)