/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The default value for a multiple version picker custom field.
 *
 * @param type, required
 * @param versionIds, required, The IDs of the default versions.
 * @param versionOrder, optional, The order the pickable versions are displayed in. If not provided, the released-first order is used. Available version orders are `"releasedFirst"` and `"unreleasedFirst"`.
 */
@Serializable
data class CustomFieldContextDefaultValueMultipleVersionPicker(
    @SerialName("type") val type: String,
    @SerialName("versionIds") val versionIds: List<String>,
    @SerialName("versionOrder") val versionOrder: String? = null
)