/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The default value for a version picker custom field.
 *
 * @param type, required
 * @param versionId, required, The ID of the default version.
 * @param versionOrder, optional, The order the pickable versions are displayed in. If not provided, the released-first order is used. Available version orders are `"releasedFirst"` and `"unreleasedFirst"`.
 */
@Serializable
data class CustomFieldContextDefaultValueSingleVersionPicker(
    @SerialName("type") val type: String,
    @SerialName("versionId") val versionId: String,
    @SerialName("versionOrder") val versionOrder: String? = null
)