/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Default value for a float (number) custom field.
 *
 * @param number, required, The default floating-point number.
 * @param type, required
 */
@Serializable
data class CustomFieldContextDefaultValueFloat(
    @SerialName("number") val number: Double,
    @SerialName("type") val type: String
)