/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The default value for a multi-select custom field.
 *
 * @param contextId, required, The ID of the context.
 * @param optionIds, required, The list of IDs of the default options.
 * @param type, required
 */
@Serializable
data class CustomFieldContextDefaultValueMultipleOption(
    @SerialName("contextId") val contextId: String,
    @SerialName("optionIds") val optionIds: List<String>,
    @SerialName("type") val type: String
)