/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Defaults for a Forge user custom field.
 *
 * @param accountId, required, The ID of the default user.
 * @param contextId, required, The ID of the context.
 * @param type, required
 * @param userFilter, optional, Filter for a User Picker (single) custom field.
 */
@Serializable
data class CustomFieldContextDefaultValueForgeUserField(
    @SerialName("accountId") val accountId: String,
    @SerialName("contextId") val contextId: String,
    @SerialName("type") val type: String,
    @SerialName("userFilter") val userFilter: UserFilter? = null
)