/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The default text for a text custom field.
 *
 * @param text, optional, The default text. The maximum length is 254 characters.
 * @param type, required
 */
@Serializable
data class CustomFieldContextDefaultValueTextField(
    @SerialName("text") val text: String? = null,
    @SerialName("type") val type: String
)