/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The default value for a Forge date time custom field.
 *
 * @param contextId, required, The ID of the context.
 * @param dateTime, optional, The default date-time in ISO format. Ignored if `useCurrent` is true.
 * @param type, required
 * @param useCurrent, optional, Whether to use the current date.
 */
@Serializable
data class CustomFieldContextDefaultValueForgeDateTimeField(
    @SerialName("contextId") val contextId: String,
    @SerialName("dateTime") val dateTime: String? = null,
    @SerialName("type") val type: String,
    @SerialName("useCurrent") val useCurrent: Boolean = false
)