/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details of the settings for a dashboard gadget.
 *
 * @param color, optional, The color of the gadget. Should be one of `blue`, `red`, `yellow`, `green`, `cyan`, `purple`, `gray`, or `white`.
 * @param ignoreUriAndModuleKeyValidation, optional, Whether to ignore the validation of module key and URI. For example, when a gadget is created that is a part of an application that isn't installed.
 * @param moduleKey, optional, The module key of the gadget type. Can't be provided with `uri`.
 * @param position, optional, The position of the gadget. When the gadget is placed into the position, other gadgets in the same column are moved down to accommodate it.
 * @param title, optional, The title of the gadget.
 * @param uri, optional, The URI of the gadget type. Can't be provided with `moduleKey`.
 */
@Serializable
data class DashboardGadgetSettings(
    @SerialName("color") val color: String? = null,
    @SerialName("ignoreUriAndModuleKeyValidation") val ignoreUriAndModuleKeyValidation: Boolean? = null,
    @SerialName("moduleKey") val moduleKey: String? = null,
    @SerialName("position") val position: position? = null,
    @SerialName("title") val title: String? = null,
    @SerialName("uri") val uri: String? = null
)