/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The list of gadgets on the dashboard.
 *
 * @param gadgets, required, The list of gadgets.
 */
@Serializable
data class DashboardGadgetResponse(
    @SerialName("gadgets") val gadgets: List<DashboardGadget>
)