/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a gadget position.
 *
 * @param theColumnPositionOfTheGadget, required
 * @param theRowPositionOfTheGadget, required
 */
@Serializable
data class DashboardGadgetPosition(
    @SerialName("theColumnPositionOfTheGadget") val theColumnPositionOfTheGadget: Int,
    @SerialName("theRowPositionOfTheGadget") val theRowPositionOfTheGadget: Int
)