/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The data classification.
 *
 * @param classifications, optional, The data classifications.
 */
@Serializable
data class DataClassificationLevelsBean(
    @SerialName("classifications") val classifications: List<DataClassificationTagBean>? = null
)