/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param customFieldReplacementList, optional, An array of custom field IDs (`customFieldId`) and version IDs (`moveTo`) to update when the fields contain the deleted version.
 * @param moveAffectedIssuesTo, optional, The ID of the version to update `affectedVersion` to when the field contains the deleted version.
 * @param moveFixIssuesTo, optional, The ID of the version to update `fixVersion` to when the field contains the deleted version.
 */
@Serializable
data class DeleteAndReplaceVersionBean(
    @SerialName("customFieldReplacementList") val customFieldReplacementList: List<CustomFieldReplacement>? = null,
    @SerialName("moveAffectedIssuesTo") val moveAffectedIssuesTo: Long? = null,
    @SerialName("moveFixIssuesTo") val moveFixIssuesTo: Long? = null
)