/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details about a workflow.
 *
 * @param default, optional
 * @param description, optional, The description of the workflow.
 * @param lastModifiedDate, optional, The datetime the workflow was last modified.
 * @param lastModifiedUser, optional, This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
 * @param lastModifiedUserAccountId, optional, The account ID of the user that last modified the workflow.
 * @param name, optional, The name of the workflow.
 * @param scope, optional, The scope where this workflow applies
 * @param steps, optional, The number of steps included in the workflow.
 */
@Serializable
data class DeprecatedWorkflow(
    @SerialName("default") val default: Boolean? = null,
    @SerialName("description") val description: String? = null,
    @SerialName("lastModifiedDate") val lastModifiedDate: String? = null,
    @SerialName("lastModifiedUser") val lastModifiedUser: String? = null,
    @SerialName("lastModifiedUserAccountId") val lastModifiedUserAccountId: String? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("scope") val scope: scope? = null,
    @SerialName("steps") val steps: Int? = null
)