/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The response for status request for a running/completed export task.
 *
 * @param fileUrl, optional
 * @param payload, optional
 * @param progress, optional
 * @param status, optional
 * @param submittedTime, optional
 * @param taskId, optional
 */
@Serializable
data class ExportArchivedIssuesTaskProgressResponse(
    @SerialName("fileUrl") val fileUrl: String? = null,
    @SerialName("payload") val payload: String? = null,
    @SerialName("progress") val progress: Long? = null,
    @SerialName("status") val status: String? = null,
    @SerialName("submittedTime") val submittedTime: String? = null,
    @SerialName("taskId") val taskId: String? = null
)