/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details about a failed webhook.
 *
 * @param body, optional, The webhook body.
 * @param failureTime, required, The time the webhook was added to the list of failed webhooks (that is, the time of the last failed retry).
 * @param id, required, The webhook ID, as sent in the `X-Atlassian-Webhook-Identifier` header with the webhook.
 * @param url, required, The original webhook destination.
 */
@Serializable
data class FailedWebhook(
    @SerialName("body") val body: String? = null,
    @SerialName("failureTime") val failureTime: Long,
    @SerialName("id") val id: String,
    @SerialName("url") val url: String
)