/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A clause that asserts the current value of a field. For example, `summary ~ test`.
 *
 * @param jqlQueryField, optional, A field used in a JQL query. See [Advanced searching - fields reference](https://confluence.atlassian.com/x/dAiiLQ) for more information about fields in JQL queries.
 * @param jqlQueryClauseOperand, optional, Details of an operand in a JQL clause.
 * @param operator, required, The operator between the field and operand.
 */
@Serializable
data class FieldValueClause(
    @SerialName("jqlQueryField") val jqlQueryField: JqlQueryField? = null,
    @SerialName("jqlQueryClauseOperand") val jqlQueryClauseOperand: JqlQueryClauseOperand? = null,
    @SerialName("operator") val operator: String
)