/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a field.
 *
 * @param contextsCount, optional, Number of contexts where the field is used.
 * @param description, optional, The description of the field.
 * @param id, required, The ID of the field.
 * @param isLocked, optional, Whether the field is locked.
 * @param isUnscreenable, optional, Whether the field is shown on screen or not.
 * @param key, optional, The key of the field.
 * @param fieldLastUsed, optional, Information about the most recent use of a field.
 * @param name, required, The name of the field.
 * @param projectsCount, optional, Number of projects where the field is used.
 * @param jsonTypeBean, optional, The schema of a field.
 * @param screensCount, optional, Number of screens where the field is used.
 * @param searcherKey, optional, The searcher key of the field. Returned for custom fields.
 * @param stableId, optional, The stable ID of the field.
 */
@Serializable
data class Field(
    @SerialName("contextsCount") val contextsCount: Long? = null,
    @SerialName("description") val description: String? = null,
    @SerialName("id") val id: String,
    @SerialName("isLocked") val isLocked: Boolean? = null,
    @SerialName("isUnscreenable") val isUnscreenable: Boolean? = null,
    @SerialName("key") val key: String? = null,
    @SerialName("fieldLastUsed") val fieldLastUsed: FieldLastUsed? = null,
    @SerialName("name") val name: String,
    @SerialName("projectsCount") val projectsCount: Long? = null,
    @SerialName("jsonTypeBean") val jsonTypeBean: JsonTypeBean? = null,
    @SerialName("screensCount") val screensCount: Long? = null,
    @SerialName("searcherKey") val searcherKey: String? = null,
    @SerialName("stableId") val stableId: String? = null
)