/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a field configuration scheme.
 *
 * @param description, optional, The description of the field configuration scheme.
 * @param id, required, The ID of the field configuration scheme.
 * @param name, required, The name of the field configuration scheme.
 */
@Serializable
data class FieldConfigurationScheme(
    @SerialName("description") val description: String? = null,
    @SerialName("id") val id: String,
    @SerialName("name") val name: String
)