/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A field within a field configuration.
 *
 * @param description, optional, The description of the field within the field configuration.
 * @param id, required, The ID of the field within the field configuration.
 * @param isHidden, optional, Whether the field is hidden in the field configuration.
 * @param isRequired, optional, Whether the field is required in the field configuration.
 * @param renderer, optional, The renderer type for the field within the field configuration.
 */
@Serializable
data class FieldConfigurationItem(
    @SerialName("description") val description: String? = null,
    @SerialName("id") val id: String,
    @SerialName("isHidden") val isHidden: Boolean? = null,
    @SerialName("isRequired") val isRequired: Boolean? = null,
    @SerialName("renderer") val renderer: String? = null
)