/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details of a field that can be used in advanced searches.
 *
 * @param auto, optional, Whether the field provide auto-complete suggestions.
 * @param cfid, optional, If the item is a custom field, the ID of the custom field.
 * @param deprecated, optional, Whether this field has been deprecated.
 * @param deprecatedSearcherKey, optional, The searcher key of the field, only passed when the field is deprecated.
 * @param displayName, optional, The display name contains the following:

 *  for system fields, the field name. For example, `Summary`.
 *  for collapsed custom fields, the field name followed by a hyphen and then the field name and field type. For example, `Component - Component[Dropdown]`.
 *  for other custom fields, the field name followed by a hyphen and then the custom field ID. For example, `Component - cf[10061]`.
 * @param operators, optional, The valid search operators for the field.
 * @param orderable, optional, Whether the field can be used in a query's `ORDER BY` clause.
 * @param searchable, optional, Whether the content of this field can be searched.
 * @param types, optional, The data types of items in the field.
 * @param value, optional, The field identifier.
 */
@Serializable
data class FieldReferenceData(
    @SerialName("auto") val auto: String? = null,
    @SerialName("cfid") val cfid: String? = null,
    @SerialName("deprecated") val deprecated: String? = null,
    @SerialName("deprecatedSearcherKey") val deprecatedSearcherKey: String? = null,
    @SerialName("displayName") val displayName: String? = null,
    @SerialName("operators") val operators: List<String>? = null,
    @SerialName("orderable") val orderable: String? = null,
    @SerialName("searchable") val searchable: String? = null,
    @SerialName("types") val types: List<String>? = null,
    @SerialName("value") val value: String? = null
)