/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Can contain multiple field values of following types depending on `type` key
 *
 * @param retain, optional, If `true`, will try to retain original non-null issue field values on move.
 * @param type, optional
 * @param value, optional
 */
@Serializable
data class fields(
    @SerialName("retain") val retain: Boolean = true,
    @SerialName("type") val type: String? = null,
    @SerialName("value") val value: value? = null
)