/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of an operation to perform on a field.
 *
 * @param add, optional, The value to add to the field.
 * @param copy, optional, The field value to copy from another issue.
 * @param edit, optional, The value to edit in the field.
 * @param remove, optional, The value to removed from the field.
 * @param set, optional, The value to set in the field.
 */
@Serializable
data class FieldUpdateOperation(
    @SerialName("add") val add: String? = null,
    @SerialName("copy") val copy: String? = null,
    @SerialName("edit") val edit: String? = null,
    @SerialName("remove") val remove: String? = null,
    @SerialName("set") val set: String? = null
)