/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a user or group subscribing to a filter.
 *
 * @param group, optional, The group subscribing to filter.
 * @param id, optional, The ID of the filter subscription.
 * @param user, optional, The user subscribing to filter.
 */
@Serializable
data class FilterSubscription(
    @SerialName("group") val group: GroupName? = null,
    @SerialName("id") val id: Long? = null,
    @SerialName("user") val user: User? = null
)