/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The list of groups found in a search, including header text (Showing X of Y matching groups) and total of matched groups.
 *
 * @param groups, optional
 * @param header, optional, Header text indicating the number of groups in the response and the total number of groups found in the search.
 * @param total, optional, The total number of groups found in the search.
 */
@Serializable
data class FoundGroups(
    @SerialName("groups") val groups: List<FoundGroup>? = null,
    @SerialName("header") val header: String? = null,
    @SerialName("total") val total: Int? = null
)