/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A group found in a search.
 *
 * @param groupId, optional, The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*.
 * @param html, optional, The group name with the matched query string highlighted with the HTML bold tag.
 * @param labels, optional
 * @param name, optional, The name of the group. The name of a group is mutable, to reliably identify a group use ``groupId`.`
 */
@Serializable
data class FoundGroup(
    @SerialName("groupId") val groupId: String? = null,
    @SerialName("html") val html: String? = null,
    @SerialName("labels") val labels: List<GroupLabel>? = null,
    @SerialName("name") val name: String? = null
)