/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An operand that is a function. See [Advanced searching - functions reference](https://confluence.atlassian.com/x/dwiiLQ) for more information about JQL functions.
 *
 * @param arguments, required, The list of function arguments.
 * @param encodedOperand, optional, Encoded operand, which can be used directly in a JQL query.
 * @param function, required, The name of the function.
 */
@Serializable
data class FunctionOperand(
    @SerialName("arguments") val arguments: List<String>,
    @SerialName("encodedOperand") val encodedOperand: String? = null,
    @SerialName("function") val function: String
)