/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param capacity, optional, The capacity for the Atlassian team.
 * @param id, required, The Atlassian team ID.
 * @param issueSourceId, optional, The ID of the issue source for the Atlassian team.
 * @param planningStyle, required, The planning style for the Atlassian team. This is "Scrum" or "Kanban".
 * @param sprintLength, optional, The sprint length for the Atlassian team.
 */
@Serializable
data class GetAtlassianTeamResponse(
    @SerialName("capacity") val capacity: Double? = null,
    @SerialName("id") val id: String,
    @SerialName("issueSourceId") val issueSourceId: Long? = null,
    @SerialName("planningStyle") val planningStyle: String,
    @SerialName("sprintLength") val sprintLength: Long? = null
)