/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param id, required, The plan ID.
 * @param issueSources, optional, The issue sources included in the plan.
 * @param name, required, The plan name.
 * @param status, required, The plan status. This is "Active", "Trashed" or "Archived".
 */
@Serializable
data class GetPlanResponseForPage(
    @SerialName("id") val id: String,
    @SerialName("issueSources") val issueSources: List<GetIssueSourceResponse>? = null,
    @SerialName("name") val name: String,
    @SerialName("status") val status: String
)