/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 *
 * @param expand, optional, Expand options that include additional group details in the response.
 * @param groupId, optional, The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*.
 * @param name, optional, The name of group.
 * @param self, optional, The URL for these group details.
 * @param users, optional, A paginated list of the users that are members of the group. A maximum of 50 users is returned in the list, to access additional users append `[start-index:end-index]` to the expand request. For example, to access the next 50 users, use`?expand=users[51:100]`.
 */
@Serializable
data class Group(
    @SerialName("expand") val expand: String? = null,
    @SerialName("groupId") val groupId: String? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("self") val self: String? = null,
    @SerialName("users") val users: users? = null
)