/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details about a group.
 *
 * @param groupId, optional, The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*.
 * @param name, optional, The name of the group.
 */
@Serializable
data class GroupDetails(
    @SerialName("groupId") val groupId: String? = null,
    @SerialName("name") val name: String? = null
)