/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A group label.
 *
 * @param text, optional, The group label name.
 * @param title, optional, The title of the group label.
 * @param type, optional, The type of the group label.
 */
@Serializable
data class GroupLabel(
    @SerialName("text") val text: String? = null,
    @SerialName("title") val title: String? = null,
    @SerialName("type") val type: String? = null
)