/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The project issue type hierarchy.
 *
 * @param baseLevelId, optional, The ID of the base level. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/).
 * @param levels, optional, Details about the hierarchy level.
 */
@Serializable
data class Hierarchy(
    @SerialName("baseLevelId") val baseLevelId: Long? = null,
    @SerialName("levels") val levels: List<SimplifiedHierarchyLevel>? = null
)