/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of user or system associated with a issue history metadata item.
 *
 * @param avatarUrl, optional, The URL to an avatar for the user or system associated with a history record.
 * @param displayName, optional, The display name of the user or system associated with a history record.
 * @param displayNameKey, optional, The key of the display name of the user or system associated with a history record.
 * @param id, optional, The ID of the user or system associated with a history record.
 * @param type, optional, The type of the user or system associated with a history record.
 * @param url, optional, The URL of the user or system associated with a history record.
 */
@Serializable
data class HistoryMetadataParticipant(
    @SerialName("avatarUrl") val avatarUrl: String? = null,
    @SerialName("displayName") val displayName: String? = null,
    @SerialName("displayNameKey") val displayNameKey: String? = null,
    @SerialName("id") val id: String? = null,
    @SerialName("type") val type: String? = null,
    @SerialName("url") val url: String? = null
)