/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An icon. If no icon is defined:

 *  for a status icon, no status icon displays in Jira.
 *  for the remote object icon, the default link icon displays in Jira.
 *
 * @param link, optional, The URL of the tooltip, used only for a status icon. If not set, the status icon in Jira is not clickable.
 * @param title, optional, The title of the icon. This is used as follows:

 *  For a status icon it is used as a tooltip on the icon. If not set, the status icon doesn't display a tooltip in Jira.
 *  For the remote object icon it is used in conjunction with the application name to display a tooltip for the link's icon. The tooltip takes the format "\[application name\] icon title". Blank itemsare excluded from the tooltip title. If both items are blank, the icon tooltop displays as "Web Link".
 * @param url16x16, optional, The URL of an icon that displays at 16x16 pixel in Jira.
 */
@Serializable
data class Icon(
    @SerialName("link") val link: String? = null,
    @SerialName("title") val title: String? = null,
    @SerialName("url16x16") val url16x16: String? = null
)