/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param id, optional, The ID of the referenced item.
 * @param key, optional, The key of the referenced item.
 */
@Serializable
data class IdOrKeyBean(
    @SerialName("id") val id: Long? = null,
    @SerialName("key") val key: String? = null
)