/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Result of your JQL search. Returns a list of issue IDs and a token to fetch the next page if one exists.
 *
 * @param issueIds, optional, The list of issue IDs found by the search.
 * @param nextPageToken, optional, Continuation token to fetch the next page. If this result represents the last or the only page this token will be null.
 */
@Serializable
data class IdSearchResults(
    @SerialName("issueIds") val issueIds: List<Long>? = null,
    @SerialName("nextPageToken") val nextPageToken: String? = null
)