/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param jql, optional, A [JQL](https://confluence.atlassian.com/x/egORLQ) expression. Order by clauses are not allowed.
 * @param maxResults, optional, The maximum number of items to return per page.
 * @param nextPageToken, optional, The continuation token to fetch the next page. This token is provided by the response of this endpoint.
 */
@Serializable
data class IdSearchRequestBean(
    @SerialName("jql") val jql: String? = null,
    @SerialName("maxResults") val maxResults: Int = 1000,
    @SerialName("nextPageToken") val nextPageToken: String? = null
)