/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 *
 * @param inputStream, optional
 */
@Serializable
data class InputStreamSource(
    @SerialName("inputStream") val inputStream: inputStream? = null
)