/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of an issue type scheme.
 *
 * @param defaultIssueTypeId, optional, The ID of the default issue type of the issue type scheme.
 * @param description, optional, The description of the issue type scheme.
 * @param id, required, The ID of the issue type scheme.
 * @param isDefault, optional, Whether the issue type scheme is the default.
 * @param name, required, The name of the issue type scheme.
 */
@Serializable
data class IssueTypeScheme(
    @SerialName("defaultIssueTypeId") val defaultIssueTypeId: String? = null,
    @SerialName("description") val description: String? = null,
    @SerialName("id") val id: String,
    @SerialName("isDefault") val isDefault: Boolean? = null,
    @SerialName("name") val name: String
)