/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param avatarId, optional, The ID of an issue type avatar.
 * @param description, optional, The description of the issue type.
 * @param name, optional, The unique name for the issue type. The maximum length is 60 characters.
 */
@Serializable
data class IssueTypeUpdateBean(
    @SerialName("avatarId") val avatarId: Long? = null,
    @SerialName("description") val description: String? = null,
    @SerialName("name") val name: String? = null
)