/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Number of archived/unarchived issues and list of errors that occurred during the action, if any.
 *
 * @param errors, optional
 * @param numberOfIssuesUpdated, optional
 */
@Serializable
data class IssueArchivalSyncResponse(
    @SerialName("errors") val errors: Errors? = null,
    @SerialName("numberOfIssuesUpdated") val numberOfIssuesUpdated: Long? = null
)