/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A type of issue suggested for use in auto-completion.
 *
 * @param id, optional, The ID of the type of issues suggested for use in auto-completion.
 * @param issues, optional, A list of issues suggested for use in auto-completion.
 * @param label, optional, The label of the type of issues suggested for use in auto-completion.
 * @param msg, optional, If no issue suggestions are found, returns a message indicating no suggestions were found,
 * @param sub, optional, If issue suggestions are found, returns a message indicating the number of issues suggestions found and returned.
 */
@Serializable
data class IssuePickerSuggestionsIssueType(
    @SerialName("id") val id: String? = null,
    @SerialName("issues") val issues: List<SuggestedIssue>? = null,
    @SerialName("label") val label: String? = null,
    @SerialName("msg") val msg: String? = null,
    @SerialName("sub") val sub: String? = null
)