/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Bulk operation filter details.
 *
 * @param currentValue, optional, The value of properties to perform the bulk operation on.
 * @param entityIds, optional, List of issues to perform the bulk delete operation on.
 */
@Serializable
data class IssueFilterForBulkPropertyDelete(
    @SerialName("currentValue") val currentValue: String? = null,
    @SerialName("entityIds") val entityIds: List<Long>? = null
)