/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Issue type scheme with a list of the projects that use it.
 *
 * @param issueTypeScheme, required, Details of an issue type scheme.
 * @param projectIds, required, The IDs of the projects using the issue type scheme.
 */
@Serializable
data class IssueTypeSchemeProjects(
    @SerialName("issueTypeScheme") val issueTypeScheme: IssueTypeScheme,
    @SerialName("projectIds") val projectIds: List<String>
)