/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A list of issue link type beans.
 *
 * @param issueLinkTypes, optional, The issue link type bean.
 */
@Serializable
data class IssueLinkTypes(
    @SerialName("issueLinkTypes") val issueLinkTypes: List<IssueLinkType>? = null
)