/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The wrapper for the issue creation metadata for a list of projects.
 *
 * @param expand, optional, Expand options that include additional project details in the response.
 * @param projects, optional, List of projects and their issue creation metadata.
 */
@Serializable
data class IssueCreateMetadata(
    @SerialName("expand") val expand: String? = null,
    @SerialName("projects") val projects: List<ProjectIssueCreateMetadata>? = null
)