/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Lists of issues and entity properties. See [Entity properties](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/) for more information.
 *
 * @param entitiesIds, optional, A list of entity property IDs.
 * @param properties, optional, A list of entity property keys and values.
 */
@Serializable
data class IssueEntityProperties(
    @SerialName("entitiesIds") val entitiesIds: List<Long>? = null,
    @SerialName("properties") val properties: properties? = null
)