/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * An issue ID with entity property values. See [Entity properties](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/) for more information.
 *
 * @param issueID, optional, The ID of the issue.
 * @param properties, optional, Entity properties to set on the issue. The maximum length of an issue property value is 32768 characters.
 */
@Serializable
data class IssueEntityPropertiesForMultiUpdate(
    @SerialName("issueID") val issueID: Long? = null,
    @SerialName("properties") val properties: properties? = null
)