/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * List of changelogs that belong to single issue
 *
 * @param changeHistories, optional, List of changelogs that belongs to given issueId.
 * @param issueId, optional, The ID of the issue.
 */
@Serializable
data class IssueChangeLog(
    @SerialName("changeHistories") val changeHistories: List<Changelog>? = null,
    @SerialName("issueId") val issueId: String? = null
)