/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param ids, required, The list of comment IDs. A maximum of 1000 IDs can be specified.
 */
@Serializable
data class IssueCommentListRequestBean(
    @SerialName("ids") val ids: List<Long>
)