/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details of a link between issues.
 *
 * @param id, optional, The ID of the issue link.
 * @param inwardIssue, required, Provides details about the linked issue. If presenting this link in a user interface, use the `inward` field of the issue link type to label the link.
 * @param outwardIssue, required, Provides details about the linked issue. If presenting this link in a user interface, use the `outward` field of the issue link type to label the link.
 * @param self, optional, The URL of the issue link.
 * @param type, required, The type of link between the issues.
 */
@Serializable
data class IssueLink(
    @SerialName("id") val id: String? = null,
    @SerialName("inwardIssue") val inwardIssue: inwardIssue,
    @SerialName("outwardIssue") val outwardIssue: outwardIssue,
    @SerialName("self") val self: String? = null,
    @SerialName("type") val type: type
)