/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The details of an issue type screen scheme.
 *
 * @param description, optional, The description of the issue type screen scheme. The maximum length is 255 characters.
 * @param issueTypeMappings, required, The IDs of the screen schemes for the issue type IDs and *default*. A *default* entry is required to create an issue type screen scheme, it defines the mapping for all issue types without a screen scheme.
 * @param name, required, The name of the issue type screen scheme. The name must be unique. The maximum length is 255 characters.
 */
@Serializable
data class IssueTypeScreenSchemeDetails(
    @SerialName("description") val description: String? = null,
    @SerialName("issueTypeMappings") val issueTypeMappings: List<IssueTypeScreenSchemeMapping>,
    @SerialName("name") val name: String
)