/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Issue type screen scheme with a list of the projects that use it.
 *
 * @param issueTypeScreenScheme, required, Details of an issue type screen scheme.
 * @param projectIds, required, The IDs of the projects using the issue type screen scheme.
 */
@Serializable
data class IssueTypeScreenSchemesProjects(
    @SerialName("issueTypeScreenScheme") val issueTypeScreenScheme: issueTypeScreenScheme,
    @SerialName("projectIds") val projectIds: List<String>
)