/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Describes the error that occurred when retrieving data for a particular issue.
 *
 * @param errorMessage, optional, The error that occurred when fetching this issue.
 * @param id, optional, The ID of the issue.
 */
@Serializable
data class IssueError(
    @SerialName("errorMessage") val errorMessage: String? = null,
    @SerialName("id") val id: String? = null
)