/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of an issue type scheme and its associated issue types.
 *
 * @param defaultIssueTypeId, optional, The ID of the default issue type of the issue type scheme. This ID must be included in `issueTypeIds`.
 * @param description, optional, The description of the issue type scheme. The maximum length is 4000 characters.
 * @param issueTypeIds, required, The list of issue types IDs of the issue type scheme. At least one standard issue type ID is required.
 * @param name, required, The name of the issue type scheme. The name must be unique. The maximum length is 255 characters.
 */
@Serializable
data class IssueTypeSchemeDetails(
    @SerialName("defaultIssueTypeId") val defaultIssueTypeId: String? = null,
    @SerialName("description") val description: String? = null,
    @SerialName("issueTypeIds") val issueTypeIds: List<String>,
    @SerialName("name") val name: String
)