/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details of an issue transition.
 *
 * @param expand, optional, Expand options that include additional transition details in the response.
 * @param fields, optional, Details of the fields associated with the issue transition screen. Use this information to populate `fields` and `update` in a transition request.
 * @param hasScreen, optional, Whether there is a screen associated with the issue transition.
 * @param id, optional, The ID of the issue transition. Required when specifying a transition to undertake.
 * @param isAvailable, optional, Whether the transition is available to be performed.
 * @param isConditional, optional, Whether the issue has to meet criteria before the issue transition is applied.
 * @param isGlobal, optional, Whether the issue transition is global, that is, the transition is applied to issues regardless of their status.
 * @param isInitial, optional, Whether this is the initial issue transition for the workflow.
 * @param looped, optional
 * @param name, optional, The name of the issue transition.
 * @param to, optional, Details of the issue status after the transition.
 */
@Serializable
data class IssueTransition(
    @SerialName("expand") val expand: String? = null,
    @SerialName("fields") val fields: fields? = null,
    @SerialName("hasScreen") val hasScreen: Boolean? = null,
    @SerialName("id") val id: String? = null,
    @SerialName("isAvailable") val isAvailable: Boolean? = null,
    @SerialName("isConditional") val isConditional: Boolean? = null,
    @SerialName("isGlobal") val isGlobal: Boolean? = null,
    @SerialName("isInitial") val isInitial: Boolean? = null,
    @SerialName("looped") val looped: Boolean? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("to") val to: to? = null
)