/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param issueUpdates, optional
 */
@Serializable
data class IssuesUpdateBean(
    @SerialName("issueUpdates") val issueUpdates: List<IssueUpdateDetails>? = null
)