/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Issue Bulk Transition Payload
 *
 * @param bulkTransitionInputs, required, List of objects and each object has two properties:

 *  Issues that will be bulk transitioned.
 *  TransitionId that corresponds to a specific transition of issues that share the same workflow.
 * @param sendBulkNotification, optional, A boolean value that indicates whether to send a bulk change notification when the issues are being transitioned.

If `true`, dispatches a bulk notification email to users about the updates.
 */
@Serializable
data class IssueBulkTransitionPayload(
    @SerialName("bulkTransitionInputs") val bulkTransitionInputs: List<BulkTransitionSubmitInput>,
    @SerialName("sendBulkNotification") val sendBulkNotification: Boolean = true
)