/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Status details for an issue type.
 *
 * @param id, required, The ID of the issue type.
 * @param name, required, The name of the issue type.
 * @param self, required, The URL of the issue type's status details.
 * @param statuses, required, List of status details for the issue type.
 * @param subtask, required, Whether this issue type represents subtasks.
 */
@Serializable
data class IssueTypeWithStatus(
    @SerialName("id") val id: String,
    @SerialName("name") val name: String,
    @SerialName("self") val self: String,
    @SerialName("statuses") val statuses: List<StatusDetails>,
    @SerialName("subtask") val subtask: Boolean
)