/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A list of issue type screen scheme mappings.
 *
 * @param issueTypeMappings, required, The list of issue type to screen scheme mappings. A *default* entry cannot be specified because a default entry is added when an issue type screen scheme is created.
 */
@Serializable
data class IssueTypeScreenSchemeMappingDetails(
    @SerialName("issueTypeMappings") val issueTypeMappings: List<IssueTypeScreenSchemeMapping>
)