/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The screen scheme for an issue type.
 *
 * @param issueTypeId, required, The ID of the issue type or *default*. Only issue types used in classic projects are accepted. When creating an issue screen scheme, an entry for *default* must be provided and defines the mapping for all issue types without a screen scheme. Otherwise, a *default* entry can't be provided.
 * @param issueTypeScreenSchemeId, required, The ID of the issue type screen scheme.
 * @param screenSchemeId, required, The ID of the screen scheme.
 */
@Serializable
data class IssueTypeScreenSchemeItem(
    @SerialName("issueTypeId") val issueTypeId: String,
    @SerialName("issueTypeScreenSchemeId") val issueTypeScreenSchemeId: String,
    @SerialName("screenSchemeId") val screenSchemeId: String
)