/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The JQL specifying the issues available in the evaluated Jira expression under the `issues` context variable. Not all issues returned by the JQL query are loaded, only those described by the `nextPageToken` and `maxResults` properties. This bean will be replacing JexpJqlIssues bean as part of new `evaluate` endpoint
 *
 * @param maxResults, optional, The maximum number of issues to return from the JQL query. max results value considered may be lower than the number specific here.
 * @param nextPageToken, optional, The token for a page to fetch that is not the first page. The first page has a `nextPageToken` of `null`. Use the `nextPageToken` to fetch the next page of issues.
 * @param query, optional, The JQL query, required to be bounded.
 */
@Serializable
data class JexpEvaluateCtxJqlIssues(
    @SerialName("maxResults") val maxResults: Int? = null,
    @SerialName("nextPageToken") val nextPageToken: String? = null,
    @SerialName("query") val query: String? = null
)