/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The JQL specifying the issues available in the evaluated Jira expression under the `issues` context variable.
 *
 * @param jql, optional, The JQL query that specifies the set of issues available in the Jira expression.
 */
@Serializable
data class JexpIssues(
    @SerialName("jql") val jql: JexpJqlIssues? = null
)