/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Add or clear a single select field:

 *  To add, specify the option with an `optionId`.
 *  To clear, pass an option with `optionId` as `-1`.
 *
 * @param fieldId, required
 * @param jiraSelectedOptionField, optional
 */
@Serializable
data class JiraSingleSelectField(
    @SerialName("fieldId") val fieldId: String,
    @SerialName("jiraSelectedOptionField") val jiraSelectedOptionField: JiraSelectedOptionField? = null
)