/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details about the analysed Jira expression.
 *
 * @param results, required, The results of Jira expressions analysis.
 */
@Serializable
data class JiraExpressionsAnalysis(
    @SerialName("results") val results: List<JiraExpressionAnalysis>
)