/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * The request to evaluate a Jira expression. This bean will be replacing `JiraExpressionEvaluateRequest` as part of new `evaluate` endpoint
 *
 * @param context, optional, The context in which the Jira expression is evaluated.
 * @param expression, required, The Jira expression to evaluate.
 */
@Serializable
data class JiraExpressionEvaluateRequestBean(
    @SerialName("context") val context: context? = null,
    @SerialName("expression") val expression: String
)