/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param jiraSelectedOptionField, optional
 * @param fieldId, required
 * @param jiraSelectedOptionField, optional
 */
@Serializable
data class JiraCascadingSelectField(
    @SerialName("jiraSelectedOptionField") val jiraSelectedOptionField: JiraSelectedOptionField? = null,
    @SerialName("fieldId") val fieldId: String,
    @SerialName("jiraSelectedOptionField") val jiraSelectedOptionField: JiraSelectedOptionField? = null
)