/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * The result of evaluating a Jira expression.
 *
 * @param meta, optional, Contains various characteristics of the performed expression evaluation.
 * @param value, required, The value of the evaluated expression. It may be a primitive JSON value or a Jira REST API object. (Some expressions do not produce any meaningful results—for example, an expression that returns a lambda function—if that's the case a simple string representation is returned. These string representations should not be relied upon and may change without notice.)
 */
@Serializable
data class JiraExpressionResult(
    @SerialName("meta") val meta: meta? = null,
    @SerialName("value") val value: value
)