/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param bulkEditMultiSelectFieldOption, required
 * @param components, required
 * @param fieldId, required
 */
@Serializable
data class JiraMultiSelectComponentField(
    @SerialName("bulkEditMultiSelectFieldOption") val bulkEditMultiSelectFieldOption: String,
    @SerialName("components") val components: List<JiraComponentField>,
    @SerialName("fieldId") val fieldId: String
)