/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details of Jira expressions for analysis.
 *
 * @param contextVariables, optional, Context variables and their types. The type checker assumes that [common context variables](https://developer.atlassian.com/cloud/jira/platform/jira-expressions/#context-variables), such as `issue` or `project`, are available in context and sets their type. Use this property to override the default types or provide details of new variables.
 * @param expressions, required, The list of Jira expressions to analyse.
 */
@Serializable
data class JiraExpressionForAnalysis(
    @SerialName("contextVariables") val contextVariables: contextVariables? = null,
    @SerialName("expressions") val expressions: List<String>
)