/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param jiraDateTimeInput, optional
 * @param fieldId, required
 */
@Serializable
data class JiraDateTimeField(
    @SerialName("jiraDateTimeInput") val jiraDateTimeInput: JiraDateTimeInput? = null,
    @SerialName("fieldId") val fieldId: String
)