/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Jql function precomputation.
 *
 * @param arguments, optional, The list of arguments function was invoked with.
 * @param created, optional, The timestamp of the precomputation creation.
 * @param error, optional, The error message to be displayed to the user.
 * @param field, optional, The field the function was executed against.
 * @param functionKey, optional, The function key.
 * @param functionName, optional, The name of the function.
 * @param id, optional, The id of the precomputation.
 * @param operator, optional, The operator in context of which function was executed.
 * @param updated, optional, The timestamp of the precomputation last update.
 * @param used, optional, The timestamp of the precomputation last usage.
 * @param value, optional, The JQL fragment stored as the precomputation.
 */
@Serializable
data class JqlFunctionPrecomputationBean(
    @SerialName("arguments") val arguments: List<String>? = null,
    @SerialName("created") val created: String? = null,
    @SerialName("error") val error: String? = null,
    @SerialName("field") val field: String? = null,
    @SerialName("functionKey") val functionKey: String? = null,
    @SerialName("functionName") val functionName: String? = null,
    @SerialName("id") val id: String? = null,
    @SerialName("operator") val operator: String? = null,
    @SerialName("updated") val updated: String? = null,
    @SerialName("used") val used: String? = null,
    @SerialName("value") val value: String? = null
)