/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Result of updating JQL Function precomputations.
 *
 * @param notFoundPrecomputationIDs, optional, List of precomputations that were not found and skipped. Only returned if the request passed skipNotFoundPrecomputations=true.
 */
@Serializable
data class JqlFunctionPrecomputationUpdateResponse(
    @SerialName("notFoundPrecomputationIDs") val notFoundPrecomputationIDs: List<String>? = null
)