/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * List of pairs (id and value) for precomputation updates.
 *
 * @param values, optional
 */
@Serializable
data class JqlFunctionPrecomputationUpdateRequestBean(
    @SerialName("values") val values: List<JqlFunctionPrecomputationUpdateBean>? = null
)