/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.Serializable

/**
 * Details of an operand in a JQL clause.
 *
 */
@Serializable
data class JqlQueryClauseOperand(

)