/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A parsed JQL query.
 *
 * @param jqlQueryOrderByClause, optional, Details of the order-by JQL clause.
 * @param jqlQueryClause, optional, A JQL query clause.
 */
@Serializable
data class JqlQuery(
    @SerialName("jqlQueryOrderByClause") val jqlQueryOrderByClause: JqlQueryOrderByClause? = null,
    @SerialName("jqlQueryClause") val jqlQueryClause: JqlQueryClause? = null
)