/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of an entity property.
 *
 * @param entity, required, The object on which the property is set.
 * @param key, required, The key of the property.
 * @param path, required, The path in the property value to query.
 * @param type, optional, The type of the property value extraction. Not available if the extraction for the property is not registered on the instance with the [Entity property](https://developer.atlassian.com/cloud/jira/platform/modules/entity-property/) module.
 */
@Serializable
data class JqlQueryFieldEntityProperty(
    @SerialName("entity") val entity: String,
    @SerialName("key") val key: String,
    @SerialName("path") val path: String,
    @SerialName("type") val type: String? = null
)