/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Lists of JQL reference data.
 *
 * @param jqlReservedWords, optional, List of JQL query reserved words.
 * @param visibleFieldNames, optional, List of fields usable in JQL queries.
 * @param visibleFunctionNames, optional, List of functions usable in JQL queries.
 */
@Serializable
data class JQLReferenceData(
    @SerialName("jqlReservedWords") val jqlReservedWords: List<String>? = null,
    @SerialName("visibleFieldNames") val visibleFieldNames: List<FieldReferenceData>? = null,
    @SerialName("visibleFunctionNames") val visibleFunctionNames: List<FunctionReferenceData>? = null
)