/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * The schema of a field.
 *
 * @param configuration, optional, If the field is a custom field, the configuration of the field.
 * @param custom, optional, If the field is a custom field, the URI of the field.
 * @param customId, optional, If the field is a custom field, the custom ID of the field.
 * @param items, optional, When the data type is an array, the name of the field items within the array.
 * @param system, optional, If the field is a system field, the name of the field.
 * @param type, required, The data type of the field.
 */
@Serializable
data class JsonTypeBean(
    @SerialName("configuration") val configuration: configuration? = null,
    @SerialName("custom") val custom: String? = null,
    @SerialName("customId") val customId: Long? = null,
    @SerialName("items") val items: String? = null,
    @SerialName("system") val system: String? = null,
    @SerialName("type") val type: String
)