/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details a link group, which defines issue operations.
 *
 * @param groups, optional
 * @param simpleLink, optional, Details about the operations available in this version.
 * @param id, optional
 * @param links, optional
 * @param styleClass, optional
 * @param weight, optional
 */
@Serializable
data class LinkGroup(
    @SerialName("groups") val groups: List<LinkGroup>? = null,
    @SerialName("simpleLink") val simpleLink: SimpleLink? = null,
    @SerialName("id") val id: String? = null,
    @SerialName("links") val links: List<SimpleLink>? = null,
    @SerialName("styleClass") val styleClass: String? = null,
    @SerialName("weight") val weight: Int? = null
)