/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The status mappings by workflows. Status mappings are required when the new workflow for an issue type doesn't contain all statuses that the old workflow has. Status mappings can be provided by a combination of `statusMappingsByWorkflows` and `statusMappingsByIssueTypeOverride`.
 *
 * @param newWorkflowId, required, The ID of the new workflow.
 * @param oldWorkflowId, required, The ID of the old workflow.
 * @param statusMappings, required, The list of status mappings.
 */
@Serializable
data class MappingsByWorkflow(
    @SerialName("newWorkflowId") val newWorkflowId: String,
    @SerialName("oldWorkflowId") val oldWorkflowId: String,
    @SerialName("statusMappings") val statusMappings: List<WorkflowAssociationStatusMapping>
)