/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * List of updates for a custom fields.
 *
 * @param updates, optional
 */
@Serializable
data class MultipleCustomFieldValuesUpdateDetails(
    @SerialName("updates") val updates: List<MultipleCustomFieldValuesUpdate>? = null
)