/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 *
 * @param bytes, optional
 * @param contentType, optional
 * @param empty, optional
 * @param inputStream, optional
 * @param name, optional
 * @param originalFilename, optional
 * @param resource, optional
 * @param size, optional
 */
@Serializable
data class MultipartFile(
    @SerialName("bytes") val bytes: List<String>? = null,
    @SerialName("contentType") val contentType: String? = null,
    @SerialName("empty") val empty: Boolean? = null,
    @SerialName("inputStream") val inputStream: inputStream? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("originalFilename") val originalFilename: String? = null,
    @SerialName("resource") val resource: Resource? = null,
    @SerialName("size") val size: Long? = null
)