/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A list of issues and their respective properties to set or update. See [Entity properties](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/) for more information.
 *
 * @param issues, optional, A list of issue IDs and their respective properties.
 */
@Serializable
data class MultiIssueEntityProperties(
    @SerialName("issues") val issues: List<IssueEntityPropertiesForMultiUpdate>? = null
)