/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of the group membership or permissions needed to receive the notification.
 *
 * @param groupIds, optional, List of groupId memberships required to receive the notification.
 * @param groups, optional, List of group memberships required to receive the notification.
 * @param permissions, optional, List of permissions required to receive the notification.
 */
@Serializable
data class NotificationRecipientsRestrictions(
    @SerialName("groupIds") val groupIds: List<String>? = null,
    @SerialName("groups") val groups: List<GroupName>? = null,
    @SerialName("permissions") val permissions: List<RestrictedPermission>? = null
)