/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The ID of an event that is being mapped to notifications.
 *
 * @param id, required, The ID of the notification scheme event.
 */
@Serializable
data class NotificationSchemeEventTypeId(
    @SerialName("id") val id: String
)