/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The ID of a notification scheme.
 *
 * @param id, required, The ID of a notification scheme.
 */
@Serializable
data class NotificationSchemeId(
    @SerialName("id") val id: String
)