/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details of a notification scheme event.
 *
 * @param event, required, The ID of the event.
 * @param notifications, required, The list of notifications mapped to a specified event.
 */
@Serializable
data class NotificationSchemeEventDetails(
    @SerialName("event") val event: event,
    @SerialName("notifications") val notifications: List<NotificationSchemeNotificationDetails>
)