/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a notification within a notification scheme.
 *
 * @param notificationType, required, The notification type, e.g `CurrentAssignee`, `Group`, `EmailAddress`.
 * @param parameter, optional, The value corresponding to the specified notification type.
 */
@Serializable
data class NotificationSchemeNotificationDetails(
    @SerialName("notificationType") val notificationType: String,
    @SerialName("parameter") val parameter: String? = null
)