/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An ordered list of custom field option IDs and information on where to move them.
 *
 * @param after, optional, The ID of the custom field option or cascading option to place the moved options after. Required if `position` isn't provided.
 * @param customFieldOptionIds, required, A list of IDs of custom field options to move. The order of the custom field option IDs in the list is the order they are given after the move. The list must contain custom field options or cascading options, but not both.
 * @param position, optional, The position the custom field options should be moved to. Required if `after` isn't provided.
 */
@Serializable
data class OrderOfCustomFieldOptions(
    @SerialName("after") val after: String? = null,
    @SerialName("customFieldOptionIds") val customFieldOptionIds: List<String>,
    @SerialName("position") val position: String? = null
)