/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param isLast, optional, Whether this is the last page.
 * @param maxResults, optional, The maximum number of items that could be returned.
 * @param nextPage, optional, The URL of the next page of results, if any.
 * @param self, optional, The URL of this page.
 * @param startAt, optional, The index of the first item returned on the page.
 * @param total, optional, Number of items that satisfy the search.
 * @param values, optional, The list of items.
 */
@Serializable
data class PageOfStatuses(
    @SerialName("isLast") val isLast: Boolean? = null,
    @SerialName("maxResults") val maxResults: Int? = null,
    @SerialName("nextPage") val nextPage: String? = null,
    @SerialName("self") val self: String? = null,
    @SerialName("startAt") val startAt: Long? = null,
    @SerialName("total") val total: Long? = null,
    @SerialName("values") val values: List<JiraStatus>? = null
)