/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A page of CreateMetaIssueTypes.
 *
 * @param createMetaIssueType, optional
 * @param issueTypes, optional, The list of CreateMetaIssueType.
 * @param maxResults, optional, The maximum number of items to return per page.
 * @param startAt, optional, The index of the first item returned.
 * @param total, optional, The total number of items in all pages.
 */
@Serializable
data class PageOfCreateMetaIssueTypes(
    @SerialName("createMetaIssueType") val createMetaIssueType: List<IssueTypeIssueCreateMetadata>? = null,
    @SerialName("issueTypes") val issueTypes: List<IssueTypeIssueCreateMetadata>? = null,
    @SerialName("maxResults") val maxResults: Int? = null,
    @SerialName("startAt") val startAt: Long? = null,
    @SerialName("total") val total: Long? = null
)