/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A page of CreateMetaIssueType with Field.
 *
 * @param fields, optional, The collection of FieldCreateMetaBeans.
 * @param maxResults, optional, The maximum number of items to return per page.
 * @param results, optional
 * @param startAt, optional, The index of the first item returned.
 * @param total, optional, The total number of items in all pages.
 */
@Serializable
data class PageOfCreateMetaIssueTypeWithField(
    @SerialName("fields") val fields: List<FieldCreateMetadata>? = null,
    @SerialName("maxResults") val maxResults: Int? = null,
    @SerialName("results") val results: List<FieldCreateMetadata>? = null,
    @SerialName("startAt") val startAt: Long? = null,
    @SerialName("total") val total: Long? = null
)