/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a parsed JQL query.
 *
 * @param errors, optional, The list of syntax or validation errors.
 * @param query, required, The JQL query that was parsed and validated.
 * @param structure, optional, The syntax tree of the query. Empty if the query was invalid.
 */
@Serializable
data class ParsedJqlQuery(
    @SerialName("errors") val errors: List<String>? = null,
    @SerialName("query") val query: String,
    @SerialName("structure") val structure: JqlQuery? = null
)