/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A list of parsed JQL queries.
 *
 * @param queries, required, A list of parsed JQL queries.
 */
@Serializable
data class ParsedJqlQueries(
    @SerialName("queries") val queries: List<ParsedJqlQuery>
)