/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details about permissions.
 *
 * @param permissions, optional, List of permissions.
 */
@Serializable
data class Permissions(
    @SerialName("permissions") val permissions: permissions? = null
)