/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * The ID of a priority scheme.
 *
 * @param id, optional, The ID of the priority scheme.
 * @param task, optional, The in-progress issue migration task.
 */
@Serializable
data class PrioritySchemeId(
    @SerialName("id") val id: String? = null,
    @SerialName("task") val task: task? = null
)