/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param ids, required, Affected entity ids.
 * @param mappings, optional, Instructions to migrate issues.
 */
@Serializable
data class PrioritySchemeChangesWithMappings(
    @SerialName("ids") val ids: List<Long>,
    @SerialName("mappings") val mappings: List<PriorityMapping>? = null
)