/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The hierarchy of issue types within a project.
 *
 * @param hierarchy, optional, Details of an issue type hierarchy level.
 * @param projectId, optional, The ID of the project.
 */
@Serializable
data class ProjectIssueTypeHierarchy(
    @SerialName("hierarchy") val hierarchy: List<ProjectIssueTypesHierarchyLevel>? = null,
    @SerialName("projectId") val projectId: Long? = null
)