/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details about the roles in a project.
 *
 * @param actors, optional, The list of users who act in this role.
 * @param admin, optional, Whether this role is the admin role for the project.
 * @param currentUserRole, optional, Whether the calling user is part of this role.
 * @param default, optional, Whether this role is the default role for the project
 * @param description, optional, The description of the project role.
 * @param id, optional, The ID of the project role.
 * @param name, optional, The name of the project role.
 * @param roleConfigurable, optional, Whether the roles are configurable for this project.
 * @param scope, optional, The scope of the role. Indicated for roles associated with [next-gen projects](https://confluence.atlassian.com/x/loMyO).
 * @param self, optional, The URL the project role details.
 * @param translatedName, optional, The translated name of the project role.
 */
@Serializable
data class ProjectRole(
    @SerialName("actors") val actors: List<RoleActor>? = null,
    @SerialName("admin") val admin: Boolean? = null,
    @SerialName("currentUserRole") val currentUserRole: Boolean? = null,
    @SerialName("default") val default: Boolean? = null,
    @SerialName("description") val description: String? = null,
    @SerialName("id") val id: Long? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("roleConfigurable") val roleConfigurable: Boolean? = null,
    @SerialName("scope") val scope: scope? = null,
    @SerialName("self") val self: String? = null,
    @SerialName("translatedName") val translatedName: String? = null
)