/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of the feature state.
 *
 * @param state, optional, The feature state.
 */
@Serializable
data class ProjectFeatureState(
    @SerialName("state") val state: String? = null
)