/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A project's sender email address.
 *
 * @param emailAddress, optional, The email address.
 * @param emailAddressStatus, optional, When using a custom domain, the status of the email address.
 */
@Serializable
data class ProjectEmailAddress(
    @SerialName("emailAddress") val emailAddress: String? = null,
    @SerialName("emailAddressStatus") val emailAddressStatus: List<String>? = null
)