/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The project and issue type mappings.
 *
 * @param mappings, required, The project and issue type mappings.
 */
@Serializable
data class ProjectIssueTypeMappings(
    @SerialName("mappings") val mappings: List<ProjectIssueTypeMapping>
)