/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Properties that identify a published workflow.
 *
 * @param entityId, optional, The entity ID of the workflow.
 * @param name, required, The name of the workflow.
 */
@Serializable
data class PublishedWorkflowId(
    @SerialName("entityId") val entityId: String? = null,
    @SerialName("name") val name: String
)