/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details about the status mappings for publishing a draft workflow scheme.
 *
 * @param statusMappings, optional, Mappings of statuses to new statuses for issue types.
 */
@Serializable
data class PublishDraftWorkflowScheme(
    @SerialName("statusMappings") val statusMappings: List<StatusMapping>? = null
)