/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of the identifiers for a created or updated remote issue link.
 *
 * @param id, optional, The ID of the remote issue link, such as the ID of the item on the remote system.
 * @param self, optional, The URL of the remote issue link.
 */
@Serializable
data class RemoteIssueLinkIdentifies(
    @SerialName("id") val id: Long? = null,
    @SerialName("self") val self: String? = null
)