/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The linked item.
 *
 * @param icon, optional, Details of the icon for the item. If no icon is defined, the default link icon is used in Jira.
 * @param status, optional, The status of the item.
 * @param summary, optional, The summary details of the item.
 * @param title, required, The title of the item.
 * @param url, required, The URL of the item.
 */
@Serializable
data class RemoteObject(
    @SerialName("icon") val icon: Icon? = null,
    @SerialName("status") val status: Status? = null,
    @SerialName("summary") val summary: String? = null,
    @SerialName("title") val title: String,
    @SerialName("url") val url: String
)