/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param errors, optional, A collection of errors related to unchanged issues. The collection size is limited, which means not all errors may be returned.
 * @param modifiedIssues, optional, The IDs of the modified issues.
 * @param unmodifiedIssues, optional, The IDs of the unchanged issues, those issues where errors prevent modification.
 */
@Serializable
data class RemoveOptionFromIssuesResult(
    @SerialName("errors") val errors: SimpleErrorCollection? = null,
    @SerialName("modifiedIssues") val modifiedIssues: List<Long>? = null,
    @SerialName("unmodifiedIssues") val unmodifiedIssues: List<Long>? = null
)