/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The list of required status mappings by workflow.
 *
 * @param sourceWorkflowId, optional, The ID of the source workflow.
 * @param statusIds, optional, The status IDs requiring mapping.
 * @param targetWorkflowId, optional, The ID of the target workflow.
 */
@Serializable
data class RequiredMappingByWorkflows(
    @SerialName("sourceWorkflowId") val sourceWorkflowId: String? = null,
    @SerialName("statusIds") val statusIds: List<String>? = null,
    @SerialName("targetWorkflowId") val targetWorkflowId: String? = null
)