/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A rule configuration.
 *
 * @param disabled, optional, Whether the rule is disabled.
 * @param tag, optional, A tag used to filter rules in [Get workflow transition rule configurations](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflow-transition-rules/#api-rest-api-3-workflow-rule-config-get).
 * @param value, required, Configuration of the rule, as it is stored by the Connect or the Forge app on the rule configuration page.
 */
@Serializable
data class RuleConfiguration(
    @SerialName("disabled") val disabled: Boolean = false,
    @SerialName("tag") val tag: String? = null,
    @SerialName("value") val value: String
)