/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The sanitized JQL queries for the given account IDs.
 *
 * @param queries, optional, The list of sanitized JQL queries.
 */
@Serializable
data class SanitizedJqlQueries(
    @SerialName("queries") val queries: List<SanitizedJqlQuery>? = null
)