/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a screen.
 *
 * @param description, optional, The description of the screen. The maximum length is 255 characters.
 * @param name, required, The name of the screen. The name must be unique. The maximum length is 255 characters.
 */
@Serializable
data class ScreenDetails(
    @SerialName("description") val description: String? = null,
    @SerialName("name") val name: String
)