/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * The result of a JQL search.
 *
 * @param expand, optional, Expand options that include additional search result details in the response.
 * @param issues, optional, The list of issues found by the search.
 * @param maxResults, optional, The maximum number of results that could be on the page.
 * @param names, optional, The ID and name of each field in the search results.
 * @param schema, optional, The schema describing the field types in the search results.
 * @param startAt, optional, The index of the first item returned on the page.
 * @param total, optional, The number of results on the page.
 * @param warningMessages, optional, Any warnings related to the JQL query.
 */
@Serializable
data class SearchResults(
    @SerialName("expand") val expand: String? = null,
    @SerialName("issues") val issues: List<IssueBean>? = null,
    @SerialName("maxResults") val maxResults: Int? = null,
    @SerialName("names") val names: names? = null,
    @SerialName("schema") val schema: schema? = null,
    @SerialName("startAt") val startAt: Int? = null,
    @SerialName("total") val total: Int? = null,
    @SerialName("warningMessages") val warningMessages: List<String>? = null
)