/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of how to filter and list search auto complete information.
 *
 * @param includeCollapsedFields, optional, Include collapsed fields for fields that have non-unique names.
 * @param projectIds, optional, List of project IDs used to filter the visible field details returned.
 */
@Serializable
data class SearchAutoCompleteFilter(
    @SerialName("includeCollapsedFields") val includeCollapsedFields: Boolean = false,
    @SerialName("projectIds") val projectIds: List<Long>? = null
)