/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * List of security schemes.
 *
 * @param issueSecuritySchemes, optional, List of security schemes.
 */
@Serializable
data class SecuritySchemes(
    @SerialName("issueSecuritySchemes") val issueSecuritySchemes: List<SecurityScheme>? = null
)