/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details about the Jira instance.
 *
 * @param baseUrl, optional, The base URL of the Jira instance.
 * @param buildDate, optional, The timestamp when the Jira version was built.
 * @param buildNumber, optional, The build number of the Jira version.
 * @param deploymentType, optional, The type of server deployment. This is always returned as *Cloud*.
 * @param displayUrl, optional, The display URL of the Jira instance.
 * @param displayUrlConfluence, optional, The display URL of Confluence.
 * @param displayUrlServicedeskHelpCenter, optional, The display URL of the Servicedesk Help Center.
 * @param healthChecks, optional, Jira instance health check results. Deprecated and no longer returned.
 * @param scmInfo, optional, The unique identifier of the Jira version.
 * @param serverTime, optional, The time in Jira when this request was responded to.
 * @param serverTimeZone, optional, The default timezone of the Jira server. In a format known as Olson Time Zones, IANA Time Zones or TZ Database Time Zones.
 * @param serverTitle, optional, The name of the Jira instance.
 * @param version, optional, The version of Jira.
 * @param versionNumbers, optional, The major, minor, and revision version numbers of the Jira version.
 */
@Serializable
data class ServerInformation(
    @SerialName("baseUrl") val baseUrl: String? = null,
    @SerialName("buildDate") val buildDate: String? = null,
    @SerialName("buildNumber") val buildNumber: Int? = null,
    @SerialName("deploymentType") val deploymentType: String? = null,
    @SerialName("displayUrl") val displayUrl: String? = null,
    @SerialName("displayUrlConfluence") val displayUrlConfluence: String? = null,
    @SerialName("displayUrlServicedeskHelpCenter") val displayUrlServicedeskHelpCenter: String? = null,
    @SerialName("healthChecks") val healthChecks: List<HealthCheckResult>? = null,
    @SerialName("scmInfo") val scmInfo: String? = null,
    @SerialName("serverTime") val serverTime: String? = null,
    @SerialName("serverTimeZone") val serverTimeZone: serverTimeZone? = null,
    @SerialName("serverTitle") val serverTitle: String? = null,
    @SerialName("version") val version: String? = null,
    @SerialName("versionNumbers") val versionNumbers: List<Int>? = null
)