/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The new default issue priority.
 *
 * @param id, required, The ID of the new default issue priority. Must be an existing ID or null. Setting this to null erases the default priority setting.
 */
@Serializable
data class SetDefaultPriorityRequest(
    @SerialName("id") val id: String
)