/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param accountId, optional, The user account ID that the filter is shared with. For a request, specify the `accountId` property for the user.
 * @param groupId, optional, The ID of the group, which uniquely identifies the group across all Atlassian products.For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*. Cannot be provided with `groupname`.
 * @param groupname, optional, The name of the group to share the filter with. Set `type` to `group`. Please note that the name of a group is mutable, to reliably identify a group use `groupId`.
 * @param projectId, optional, The ID of the project to share the filter with. Set `type` to `project`.
 * @param projectRoleId, optional, The ID of the project role to share the filter with. Set `type` to `projectRole` and the `projectId` for the project that the role is in.
 * @param rights, optional, The rights for the share permission.
 * @param type, required, The type of the share permission.Specify the type as follows:

 *  `user` Share with a user.
 *  `group` Share with a group. Specify `groupname` as well.
 *  `project` Share with a project. Specify `projectId` as well.
 *  `projectRole` Share with a project role in a project. Specify `projectId` and `projectRoleId` as well.
 *  `global` Share globally, including anonymous users. If set, this type overrides all existing share permissions and must be deleted before any non-global share permissions is set.
 *  `authenticated` Share with all logged-in users. This shows as `loggedin` in the response. If set, this type overrides all existing share permissions and must be deleted before any non-global share permissions is set.
 */
@Serializable
data class SharePermissionInputBean(
    @SerialName("accountId") val accountId: String? = null,
    @SerialName("groupId") val groupId: String? = null,
    @SerialName("groupname") val groupname: String? = null,
    @SerialName("projectId") val projectId: String? = null,
    @SerialName("projectRoleId") val projectRoleId: String? = null,
    @SerialName("rights") val rights: Int? = null,
    @SerialName("type") val type: String
)