/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param to, optional, The issue status change of the transition.
 * @param transitionId, optional, The unique ID of the transition.
 * @param transitionName, optional, The name of the transition.
 */
@Serializable
data class SimplifiedIssueTransition(
    @SerialName("to") val to: IssueTransitionStatus? = null,
    @SerialName("transitionId") val transitionId: Int? = null,
    @SerialName("transitionName") val transitionName: String? = null
)