/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param listWrapperCallbackApplicationRole, optional
 * @param items, optional
 * @param max-results, optional
 * @param listWrapperCallbackApplicationRole, optional
 * @param size, optional
 */
@Serializable
data class SimpleListWrapperApplicationRole(
    @SerialName("listWrapperCallbackApplicationRole") val listWrapperCallbackApplicationRole: ListWrapperCallbackApplicationRole? = null,
    @SerialName("items") val items: List<ApplicationRole>? = null,
    @SerialName("max-results") val max-results: Int? = null,
    @SerialName("listWrapperCallbackApplicationRole") val listWrapperCallbackApplicationRole: ListWrapperCallbackApplicationRole? = null,
    @SerialName("size") val size: Int? = null
)