/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param listWrapperCallbackGroupName, optional
 * @param items, optional
 * @param maxResults, optional
 * @param size, optional
 */
@Serializable
data class SimpleListWrapperGroupName(
    @SerialName("listWrapperCallbackGroupName") val listWrapperCallbackGroupName: ListWrapperCallbackGroupName? = null,
    @SerialName("items") val items: List<GroupName>? = null,
    @SerialName("maxResults") val maxResults: Int? = null,
    @SerialName("size") val size: Int? = null
)