/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 *
 * @param errorMessages, optional, The list of error messages produced by this operation. For example, "input parameter 'key' must be provided"
 * @param errors, optional, The list of errors by parameter returned by the operation. For example,"projectKey": "Project keys must start with an uppercase letter, followed by one or more uppercase alphanumeric characters."
 * @param httpStatusCode, optional
 */
@Serializable
data class SimpleErrorCollection(
    @SerialName("errorMessages") val errorMessages: List<String>? = null,
    @SerialName("errors") val errors: errors? = null,
    @SerialName("httpStatusCode") val httpStatusCode: Int? = null
)