/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param id, optional, The ID of the application property.
 * @param value, optional, The new value.
 */
@Serializable
data class SimpleApplicationPropertyBean(
    @SerialName("id") val id: String? = null,
    @SerialName("value") val value: String? = null
)