/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param boardId, optional
 * @param boardName, optional
 * @param simpleBoard, optional
 * @param totalBoardsInProject, optional
 */
@Serializable
data class SoftwareNavigationInfo(
    @SerialName("boardId") val boardId: Long? = null,
    @SerialName("boardName") val boardName: String? = null,
    @SerialName("simpleBoard") val simpleBoard: Boolean? = null,
    @SerialName("totalBoardsInProject") val totalBoardsInProject: Long? = null
)