/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A status category.
 *
 * @param colorName, optional, The name of the color used to represent the status category.
 * @param id, optional, The ID of the status category.
 * @param key, optional, The key of the status category.
 * @param name, optional, The name of the status category.
 * @param self, optional, The URL of the status category.
 */
@Serializable
data class StatusCategory(
    @SerialName("colorName") val colorName: String? = null,
    @SerialName("id") val id: Long? = null,
    @SerialName("key") val key: String? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("self") val self: String? = null
)