/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The statuses associated with each workflow.
 *
 * @param initialStatusId, optional, The ID of the initial status for the workflow.
 * @param statuses, optional, The status IDs associated with the workflow.
 * @param workflowId, optional, The ID of the workflow.
 */
@Serializable
data class StatusesPerWorkflow(
    @SerialName("initialStatusId") val initialStatusId: String? = null,
    @SerialName("statuses") val statuses: List<String>? = null,
    @SerialName("workflowId") val workflowId: String? = null
)