/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of the statuses being created and their scope.
 *
 * @param statusScope, optional, The scope of the status.
 * @param statuses, required, Details of the statuses being created.
 */
@Serializable
data class StatusCreateRequest(
    @SerialName("statusScope") val statusScope: StatusScope? = null,
    @SerialName("statuses") val statuses: List<StatusCreate>
)