/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param taskId, optional
 */
@Serializable
data class SubmittedBulkOperation(
    @SerialName("taskId") val taskId: String? = null
)