/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * List of system avatars.
 *
 * @param system, optional, A list of avatar details.
 */
@Serializable
data class SystemAvatars(
    @SerialName("system") val system: List<Avatar>? = null
)