/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details about a task.
 *
 * @param description, optional, The description of the task.
 * @param elapsedRuntime, required, The execution time of the task, in milliseconds.
 * @param finished, optional, A timestamp recording when the task was finished.
 * @param id, required, The ID of the task.
 * @param lastUpdate, required, A timestamp recording when the task progress was last updated.
 * @param message, optional, Information about the progress of the task.
 * @param progress, required, The progress of the task, as a percentage complete.
 * @param result, optional, The result of the task execution.
 * @param self, required, The URL of the task.
 * @param started, optional, A timestamp recording when the task was started.
 * @param status, required, The status of the task.
 * @param submitted, required, A timestamp recording when the task was submitted.
 * @param submittedBy, required, The ID of the user who submitted the task.
 */
@Serializable
data class TaskProgressBeanObject(
    @SerialName("description") val description: String? = null,
    @SerialName("elapsedRuntime") val elapsedRuntime: Long,
    @SerialName("finished") val finished: Long? = null,
    @SerialName("id") val id: String,
    @SerialName("lastUpdate") val lastUpdate: Long,
    @SerialName("message") val message: String? = null,
    @SerialName("progress") val progress: Long,
    @SerialName("result") val result: result? = null,
    @SerialName("self") val self: String,
    @SerialName("started") val started: Long? = null,
    @SerialName("status") val status: String,
    @SerialName("submitted") val submitted: Long,
    @SerialName("submittedBy") val submittedBy: Long
)