/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Time tracking details.
 *
 * @param originalEstimate, optional, The original estimate of time needed for this issue in readable format.
 * @param originalEstimateSeconds, optional, The original estimate of time needed for this issue in seconds.
 * @param remainingEstimate, optional, The remaining estimate of time needed for this issue in readable format.
 * @param remainingEstimateSeconds, optional, The remaining estimate of time needed for this issue in seconds.
 * @param timeSpent, optional, Time worked on this issue in readable format.
 * @param timeSpentSeconds, optional, Time worked on this issue in seconds.
 */
@Serializable
data class TimeTrackingDetails(
    @SerialName("originalEstimate") val originalEstimate: String? = null,
    @SerialName("originalEstimateSeconds") val originalEstimateSeconds: Long? = null,
    @SerialName("remainingEstimate") val remainingEstimate: String? = null,
    @SerialName("remainingEstimateSeconds") val remainingEstimateSeconds: Long? = null,
    @SerialName("timeSpent") val timeSpent: String? = null,
    @SerialName("timeSpentSeconds") val timeSpentSeconds: Long? = null
)