/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details about the time tracking provider.
 *
 * @param key, required, The key for the time tracking provider. For example, *JIRA*.
 * @param name, optional, The name of the time tracking provider. For example, *JIRA provided time tracking*.
 * @param url, optional, The URL of the configuration page for the time tracking provider app. For example, */
example/config/url*. This property is only returned if the `adminPageKey` property is set in the module descriptor of the time tracking provider app.
*/
@Serializable
data class TimeTrackingProvider(
    @SerialName("key") val key: String,
    @SerialName("name") val name: String? = null,
    @SerialName("url") val url: String? = null
)