/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * Details of a workflow transition.
 *
 * @param description, required, The description of the transition.
 * @param from, required, The statuses the transition can start from.
 * @param id, required, The ID of the transition.
 * @param name, required, The name of the transition.
 * @param properties, optional, The properties of the transition.
 * @param workflowRules, optional, A collection of transition rules.
 * @param transitionScreenDetails, optional, The details of a transition screen.
 * @param to, required, The status the transition goes to.
 * @param type, required, The type of the transition.
 */
@Serializable
data class Transition(
    @SerialName("description") val description: String,
    @SerialName("from") val from: List<String>,
    @SerialName("id") val id: String,
    @SerialName("name") val name: String,
    @SerialName("properties") val properties: properties? = null,
    @SerialName("workflowRules") val workflowRules: WorkflowRules? = null,
    @SerialName("transitionScreenDetails") val transitionScreenDetails: TransitionScreenDetails? = null,
    @SerialName("to") val to: String,
    @SerialName("type") val type: String
)