/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * List of issue transitions.
 *
 * @param expand, optional, Expand options that include additional transitions details in the response.
 * @param transitions, optional, List of issue transitions.
 */
@Serializable
data class Transitions(
    @SerialName("expand") val expand: String? = null,
    @SerialName("transitions") val transitions: List<IssueTransition>? = null
)