/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Update projects in a scheme
 *
 * @param add, optional, Projects to add to a scheme
 * @param remove, optional, Projects to remove from a scheme
 */
@Serializable
data class UpdateProjectsInSchemeRequestBean(
    @SerialName("add") val add: PrioritySchemeChangesWithoutMappings? = null,
    @SerialName("remove") val remove: PrioritySchemeChangesWithoutMappings? = null
)