/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The details of the field configuration scheme.
 *
 * @param description, optional, The description of the field configuration scheme.
 * @param name, required, The name of the field configuration scheme. The name must be unique.
 */
@Serializable
data class UpdateFieldConfigurationSchemeDetails(
    @SerialName("description") val description: String? = null,
    @SerialName("name") val name: String
)