/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The IDs of the screens for the screen types of the screen scheme.
 *
 * @param create, optional, The ID of the create screen. To remove the screen association, pass a null.
 * @param default, optional, The ID of the default screen. When specified, must include a screen ID as a default screen is required.
 * @param edit, optional, The ID of the edit screen. To remove the screen association, pass a null.
 * @param view, optional, The ID of the view screen. To remove the screen association, pass a null.
 */
@Serializable
data class UpdateScreenTypes(
    @SerialName("create") val create: String? = null,
    @SerialName("default") val default: String? = null,
    @SerialName("edit") val edit: String? = null,
    @SerialName("view") val view: String? = null
)