/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The request for updating the default project classification level.
 *
 * @param id, required, The ID of the project classification.
 */
@Serializable
data class UpdateDefaultProjectClassificationBean(
    @SerialName("id") val id: String
)