/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a permission and its availability to a user.
 *
 * @param deprecatedKey, optional, Indicate whether the permission key is deprecated. Note that deprecated keys cannot be used in the `permissions parameter of Get my permissions. Deprecated keys are not returned by Get all permissions.`
 * @param description, optional, The description of the permission.
 * @param havePermission, optional, Whether the permission is available to the user in the queried context.
 * @param id, optional, The ID of the permission. Either `id` or `key` must be specified. Use [Get all permissions](#api-rest-api-3-permissions-get) to get the list of permissions.
 * @param key, optional, The key of the permission. Either `id` or `key` must be specified. Use [Get all permissions](#api-rest-api-3-permissions-get) to get the list of permissions.
 * @param name, optional, The name of the permission.
 * @param type, optional, The type of the permission.
 */
@Serializable
data class UserPermission(
    @SerialName("deprecatedKey") val deprecatedKey: Boolean? = null,
    @SerialName("description") val description: String? = null,
    @SerialName("havePermission") val havePermission: Boolean? = null,
    @SerialName("id") val id: String? = null,
    @SerialName("key") val key: String? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("type") val type: String? = null
)