/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Filter for a User Picker (single) custom field.
 *
 * @param enabled, required, Whether the filter is enabled.
 * @param groups, optional, User groups autocomplete suggestion users must belong to. If not provided, the default values are used. A maximum of 10 groups can be provided.
 * @param roleIds, optional, Roles that autocomplete suggestion users must belong to. If not provided, the default values are used. A maximum of 10 roles can be provided.
 */
@Serializable
data class UserFilter(
    @SerialName("enabled") val enabled: Boolean,
    @SerialName("groups") val groups: List<String>? = null,
    @SerialName("roleIds") val roleIds: List<Long>? = null
)