/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The level of validation to return from the API. If no values are provided, the default would return `WARNING` and `ERROR` level validation results.
 *
 * @param levels, optional
 */
@Serializable
data class ValidationOptionsForUpdate(
    @SerialName("levels") val levels: List<String>? = null
)