/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Count of a version's unresolved issues.
 *
 * @param issuesCount, optional, Count of issues.
 * @param issuesUnresolvedCount, optional, Count of unresolved issues.
 * @param self, optional, The URL of these count details.
 */
@Serializable
data class VersionUnresolvedIssuesCount(
    @SerialName("issuesCount") val issuesCount: Long? = null,
    @SerialName("issuesUnresolvedCount") val issuesUnresolvedCount: Long? = null,
    @SerialName("self") val self: String? = null
)