/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Various counts of issues within a version.
 *
 * @param customFieldUsage, optional, List of custom fields using the version.
 * @param issueCountWithCustomFieldsShowingVersion, optional, Count of issues where a version custom field is set to the version.
 * @param issuesAffectedCount, optional, Count of issues where the `affectedVersion` is set to the version.
 * @param issuesFixedCount, optional, Count of issues where the `fixVersion` is set to the version.
 * @param self, optional, The URL of these count details.
 */
@Serializable
data class VersionIssueCounts(
    @SerialName("customFieldUsage") val customFieldUsage: List<VersionUsageInCustomField>? = null,
    @SerialName("issueCountWithCustomFieldsShowingVersion") val issueCountWithCustomFieldsShowingVersion: Long? = null,
    @SerialName("issuesAffectedCount") val issuesAffectedCount: Long? = null,
    @SerialName("issuesFixedCount") val issuesFixedCount: Long? = null,
    @SerialName("self") val self: String? = null
)