/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param after, optional, The URL (self link) of the version after which to place the moved version. Cannot be used with `position`.
 * @param position, optional, An absolute position in which to place the moved version. Cannot be used with `after`.
 */
@Serializable
data class VersionMoveBean(
    @SerialName("after") val after: String? = null,
    @SerialName("position") val position: String? = null
)