/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * List of custom fields using the version.
 *
 * @param customFieldId, optional, The ID of the custom field.
 * @param fieldName, optional, The name of the custom field.
 * @param issueCountWithVersionInCustomField, optional, Count of the issues where the custom field contains the version.
 */
@Serializable
data class VersionUsageInCustomField(
    @SerialName("customFieldId") val customFieldId: Long? = null,
    @SerialName("fieldName") val fieldName: String? = null,
    @SerialName("issueCountWithVersionInCustomField") val issueCountWithVersionInCustomField: Long? = null
)