/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The group or role to which this item is visible.
 *
 * @param identifier, optional, The ID of the group or the name of the role that visibility of this item is restricted to.
 * @param type, optional, Whether visibility of this item is restricted to a group or role.
 * @param value, optional, The name of the group or role that visibility of this item is restricted to. Please note that the name of a group is mutable, to reliably identify a group use `identifier`.
 */
@Serializable
data class Visibility(
    @SerialName("identifier") val identifier: String? = null,
    @SerialName("type") val type: String? = null,
    @SerialName("value") val value: String? = null
)