/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The date the refreshed webhooks expire.
 *
 * @param expirationDate, required, The expiration date of all the refreshed webhooks.
 */
@Serializable
data class WebhooksExpirationDate(
    @SerialName("expirationDate") val expirationDate: Long
)