/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The x and y location of the status in the workflow.
 *
 * @param x, optional, The x axis location.
 * @param y, optional, The y axis location.
 */
@Serializable
data class WorkflowStatusLayout(
    @SerialName("x") val x: Double? = null,
    @SerialName("y") val y: Double? = null
)