/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The details of the workflows to create.
 *
 * @param description, optional, The description of the workflow to create.
 * @param name, required, The name of the workflow to create.
 * @param workflowLayout, optional, The starting point for the statuses in the workflow.
 * @param statuses, required, The statuses associated with this workflow.
 * @param transitions, required, The transitions of this workflow.
 */
@Serializable
data class WorkflowCreate(
    @SerialName("description") val description: String? = null,
    @SerialName("name") val name: String,
    @SerialName("workflowLayout") val workflowLayout: WorkflowLayout? = null,
    @SerialName("statuses") val statuses: List<StatusLayoutUpdate>,
    @SerialName("transitions") val transitions: List<TransitionUpdateDTO>
)