/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param statusMappingsByIssueTypes, optional, The list of required status mappings by issue type.
 * @param statusMappingsByWorkflows, optional, The list of required status mappings by workflow.
 * @param statuses, optional, The details of the statuses in the associated workflows.
 * @param statusesPerWorkflow, optional, The statuses associated with each workflow.
 */
@Serializable
data class WorkflowSchemeUpdateRequiredMappingsResponse(
    @SerialName("statusMappingsByIssueTypes") val statusMappingsByIssueTypes: List<RequiredMappingByIssueType>? = null,
    @SerialName("statusMappingsByWorkflows") val statusMappingsByWorkflows: List<RequiredMappingByWorkflows>? = null,
    @SerialName("statuses") val statuses: List<StatusMetadata>? = null,
    @SerialName("statusesPerWorkflow") val statusesPerWorkflow: List<StatusesPerWorkflow>? = null
)