/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The details of the workflows to update.
 *
 * @param defaultStatusMappings, optional, The mapping of old to new status ID.
 * @param description, optional, The new description for this workflow.
 * @param id, required, The ID of this workflow.
 * @param workflowLayout, optional, The starting point for the statuses in the workflow.
 * @param statusMappings, optional, The mapping of old to new status ID for a specific project and issue type.
 * @param statuses, required, The statuses associated with this workflow.
 * @param transitions, required, The transitions of this workflow.
 * @param documentVersion, optional, The current version details of this workflow scheme.
 */
@Serializable
data class WorkflowUpdate(
    @SerialName("defaultStatusMappings") val defaultStatusMappings: List<StatusMigration>? = null,
    @SerialName("description") val description: String? = null,
    @SerialName("id") val id: String,
    @SerialName("workflowLayout") val workflowLayout: WorkflowLayout? = null,
    @SerialName("statusMappings") val statusMappings: List<StatusMappingDTO>? = null,
    @SerialName("statuses") val statuses: List<StatusLayoutUpdate>,
    @SerialName("transitions") val transitions: List<TransitionUpdateDTO>,
    @SerialName("documentVersion") val documentVersion: DocumentVersion? = null
)