/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The status reference and port that a transition is connected to.
 *
 * @param port, optional, The port the transition is connected to this status.
 * @param statusReference, optional, The reference of this status.
 */
@Serializable
data class WorkflowStatusAndPort(
    @SerialName("port") val port: Int? = null,
    @SerialName("statusReference") val statusReference: String? = null
)