/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.Serializable

/**
 * The workflow transition rule conditions tree.
 *
 */
@Serializable
data class WorkflowCondition(

)