/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of a worklog.
 *
 * @param author, optional, Details of the user who created the worklog.
 * @param comment, optional, A comment about the worklog in [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/). Optional when creating or updating a worklog.
 * @param created, optional, The datetime on which the worklog was created.
 * @param id, optional, The ID of the worklog record.
 * @param issueId, optional, The ID of the issue this worklog is for.
 * @param properties, optional, Details of properties for the worklog. Optional when creating or updating a worklog.
 * @param self, optional, The URL of the worklog item.
 * @param started, optional, The datetime on which the worklog effort was started. Required when creating a worklog. Optional when updating a worklog.
 * @param timeSpent, optional, The time spent working on the issue as days (\#d), hours (\#h), or minutes (\#m or \#). Required when creating a worklog if `timeSpentSeconds` isn't provided. Optional when updating a worklog. Cannot be provided if `timeSpentSecond` is provided.
 * @param timeSpentSeconds, optional, The time in seconds spent working on the issue. Required when creating a worklog if `timeSpent` isn't provided. Optional when updating a worklog. Cannot be provided if `timeSpent` is provided.
 * @param updateAuthor, optional, Details of the user who last updated the worklog.
 * @param updated, optional, The datetime on which the worklog was last updated.
 * @param visibility, optional, Details about any restrictions in the visibility of the worklog. Optional when creating or updating a worklog.
 */
@Serializable
data class Worklog(
    @SerialName("author") val author: UserDetails? = null,
    @SerialName("comment") val comment: String? = null,
    @SerialName("created") val created: String? = null,
    @SerialName("id") val id: String? = null,
    @SerialName("issueId") val issueId: String? = null,
    @SerialName("properties") val properties: List<EntityProperty>? = null,
    @SerialName("self") val self: String? = null,
    @SerialName("started") val started: String? = null,
    @SerialName("timeSpent") val timeSpent: String? = null,
    @SerialName("timeSpentSeconds") val timeSpentSeconds: Long? = null,
    @SerialName("updateAuthor") val updateAuthor: UserDetails? = null,
    @SerialName("updated") val updated: String? = null,
    @SerialName("visibility") val visibility: Visibility? = null
)