/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of workflows and related statuses.
 *
 * @param statuses, optional, List of statuses.
 * @param workflows, optional, List of workflows.
 */
@Serializable
data class WorkflowReadResponse(
    @SerialName("statuses") val statuses: List<JiraWorkflowStatus>? = null,
    @SerialName("workflows") val workflows: List<JiraWorkflow>? = null
)