/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Workflow metadata and usage detail.
 *
 * @param description, required, The description of the workflow.
 * @param id, required, The ID of the workflow.
 * @param name, required, The name of the workflow.
 * @param usage, required, Use the optional `workflows.usages` expand to get additional information about the projects and issue types associated with the workflows in the workflow scheme.
 * @param documentVersion, optional, The current version details of this workflow scheme.
 */
@Serializable
data class WorkflowMetadataRestModel(
    @SerialName("description") val description: String,
    @SerialName("id") val id: String,
    @SerialName("name") val name: String,
    @SerialName("usage") val usage: List<SimpleUsage>,
    @SerialName("documentVersion") val documentVersion: DocumentVersion? = null
)