/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A collection of transition rules.
 *
 * @param workflowCondition, optional, The workflow transition rule conditions tree.
 * @param postFunctions, optional, The workflow post functions.
 * @param validators, optional, The workflow validators.
 */
@Serializable
data class WorkflowRules(
    @SerialName("workflowCondition") val workflowCondition: WorkflowCondition? = null,
    @SerialName("postFunctions") val postFunctions: List<WorkflowTransitionRule>? = null,
    @SerialName("validators") val validators: List<WorkflowTransitionRule>? = null
)