/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The request payload to get the required mappings for updating a workflow scheme.
 *
 * @param defaultWorkflowId, optional, The ID of the new default workflow for this workflow scheme. Only used in global-scoped workflow schemes. If it isn't specified, is set to *Jira Workflow (jira)*.
 * @param id, required, The ID of the workflow scheme.
 * @param workflowsForIssueTypes, required, The new workflow to issue type mappings for this workflow scheme.
 */
@Serializable
data class WorkflowSchemeUpdateRequiredMappingsRequest(
    @SerialName("defaultWorkflowId") val defaultWorkflowId: String? = null,
    @SerialName("id") val id: String,
    @SerialName("workflowsForIssueTypes") val workflowsForIssueTypes: List<WorkflowSchemeAssociation>
)