/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Operations allowed on a workflow
 *
 * @param canDelete, required, Whether the workflow can be deleted.
 * @param canEdit, required, Whether the workflow can be updated.
 */
@Serializable
data class WorkflowOperations(
    @SerialName("canDelete") val canDelete: Boolean,
    @SerialName("canEdit") val canEdit: Boolean
)