/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The workflows that use this status. Only available if the `workflowUsages` expand is requested.
 *
 * @param workflowId, optional, Workflow ID.
 * @param workflowName, optional, Workflow name.
 */
@Serializable
data class WorkflowUsages(
    @SerialName("workflowId") val workflowId: String? = null,
    @SerialName("workflowName") val workflowName: String? = null
)