/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.*

/**
 * A workflow transition rule condition. This object returns `nodeType` as `simple`.
 *
 * @param configuration, optional, EXPERIMENTAL. The configuration of the transition rule.
 * @param nodeType, required
 * @param type, required, The type of the transition rule.
 */
@Serializable
data class WorkflowSimpleCondition(
    @SerialName("configuration") val configuration: configuration? = null,
    @SerialName("nodeType") val nodeType: String,
    @SerialName("type") val type: String
)