/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The ID and the name of the workflow scheme.
 *
 * @param id, required, The ID of the workflow scheme.
 * @param name, required, The name of the workflow scheme.
 */
@Serializable
data class WorkflowSchemeIdName(
    @SerialName("id") val id: String,
    @SerialName("name") val name: String
)