/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details about a workflow configuration update request.
 *
 * @param workflows, required, The list of workflows with transition rules to update.
 */
@Serializable
data class WorkflowTransitionRulesUpdate(
    @SerialName("workflows") val workflows: List<WorkflowTransitionRules>
)