/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details of the workflow and its transition rules.
 *
 * @param expand, optional, Use expand to include additional information in the response. This parameter accepts `transition` which, for each rule, returns information about the transition the rule is assigned to.
 * @param ruleIds, required, The list of workflow rule IDs.
 * @param workflowEntityId, required, The workflow ID.
 */
@Serializable
data class WorkflowRulesSearch(
    @SerialName("expand") val expand: String? = null,
    @SerialName("ruleIds") val ruleIds: List<String>,
    @SerialName("workflowEntityId") val workflowEntityId: String
)