/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Details about a workflow.
 *
 * @param created, optional, The creation date of the workflow.
 * @param description, required, The description of the workflow.
 * @param hasDraftWorkflow, optional, Whether the workflow has a draft version.
 * @param publishedWorkflowId, optional, Properties that identify a published workflow.
 * @param isDefault, optional, Whether this is the default workflow.
 * @param workflowOperations, optional, Operations allowed on a workflow
 * @param projects, optional, The projects the workflow is assigned to, through workflow schemes.
 * @param schemes, optional, The workflow schemes the workflow is assigned to.
 * @param statuses, optional, The statuses of the workflow.
 * @param transitions, optional, The transitions of the workflow.
 * @param updated, optional, The last edited date of the workflow.
 */
@Serializable
data class Workflow(
    @SerialName("created") val created: String? = null,
    @SerialName("description") val description: String,
    @SerialName("hasDraftWorkflow") val hasDraftWorkflow: Boolean? = null,
    @SerialName("publishedWorkflowId") val publishedWorkflowId: PublishedWorkflowId? = null,
    @SerialName("isDefault") val isDefault: Boolean? = null,
    @SerialName("workflowOperations") val workflowOperations: WorkflowOperations? = null,
    @SerialName("projects") val projects: List<ProjectDetails>? = null,
    @SerialName("schemes") val schemes: List<WorkflowSchemeIdName>? = null,
    @SerialName("statuses") val statuses: List<WorkflowStatus>? = null,
    @SerialName("transitions") val transitions: List<Transition>? = null,
    @SerialName("updated") val updated: String? = null
)