/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param workflowCreateRequest, optional, The create workflows payload.
 * @param validationOptionsForCreate, optional, The level of validation to return from the API. If no values are provided, the default would return `WARNING` and `ERROR` level validation results.
 */
@Serializable
data class WorkflowCreateValidateRequest(
    @SerialName("workflowCreateRequest") val workflowCreateRequest: WorkflowCreateRequest? = null,
    @SerialName("validationOptionsForCreate") val validationOptionsForCreate: ValidationOptionsForCreate? = null
)