/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.*
import retrofit2.http.*

interface AppMigrationApi {

    /**
     * POST /rest/atlassian-connect/1/migration/workflow/rule/search
     *
     * Returns configurations for workflow transition rules migrated from server to cloud and owned by the calling Connect app.
     * @param Atlassian-Transfer-Id The app migration transfer ID.  (example: null)
     * @param workflowRulesSearch, request body
     *
     * @return WorkflowRulesSearchDetails
     */
    @POST("/rest/atlassian-connect/1/migration/workflow/rule/search")
    suspend fun migrationResourceWorkflowRuleSearchPost(
        @Body workflowRulesSearch: WorkflowRulesSearch
    ): WorkflowRulesSearchDetails
}