/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.DataClassificationLevelsBean
import retrofit2.http.GET
import retrofit2.http.Query

interface ClassificationLevelsApi {

    /**
     * GET /rest/api/3/classification-levels
     *
     * Returns all classification levels.

     **[Permissions](#permissions) required:** None.
     * @param status Optional set of statuses to filter by. (optional) (example: null)
     * @param orderBy Ordering of the results by a given field. If not provided, values will not be sorted. (optional) (example: null)
     *
     * @return DataClassificationLevelsBean
     */
    @GET("/rest/api/3/classification-levels")
    suspend fun getAllUserDataClassificationLevels(
        @Query("status") status: List<String>? = null,
        @Query("orderBy") orderBy: String? = null
    ): DataClassificationLevelsBean
}