/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.ConnectModules
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.POST

interface DynamicModulesApi {

    /**
     * GET /rest/atlassian-connect/1/app/module/dynamic
     *
     * Returns all modules registered dynamically by the calling app.

     **[Permissions](#permissions) required:** Only Connect apps can make this request.
     *
     * @return ConnectModules
     */
    @GET("/rest/atlassian-connect/1/app/module/dynamic")
    suspend fun dynamicModulesResourceGetModulesGet(): ConnectModules

    /**
     * POST /rest/atlassian-connect/1/app/module/dynamic
     *
     * Registers a list of modules.

     **[Permissions](#permissions) required:** Only Connect apps can make this request.
     * @param connectModules, request body
     *
     * @return Unit
     */
    @POST("/rest/atlassian-connect/1/app/module/dynamic")
    suspend fun dynamicModulesResourceRegisterModulesPost(
        @Body connectModules: ConnectModules
    ): Unit
}