/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.BulkCustomFieldOptionCreateRequest
import jira.api.models.CustomFieldCreatedContextOptionsList
import jira.api.models.CustomFieldOption
import jira.api.models.PageBeanCustomFieldContextOption
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.Query

interface IssueCustomFieldOptionsApi {

    /**
     * POST /rest/api/3/field/{fieldId}/context/{contextId}/option
     *
     * Creates options and, where the custom select field is of the type Select List (cascading), cascading options for a custom select field. The options are added to a context of the field.

    The maximum number of options that can be created per request is 1000 and each field can have a maximum of 10000 options.

    This operation works for custom field options created in Jira or the operations from this resource. **To work with issue field select list options created for Connect apps use the [Issue custom field options (apps)](#api-group-issue-custom-field-options--apps-) operations.**

     **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * @param fieldId The ID of the custom field.  (example: null)
     * @param contextId The ID of the context.  (example: null)
     * @param bulkCustomFieldOptionCreateRequest, request body
     *
     * @return CustomFieldCreatedContextOptionsList
     */
    @POST("/rest/api/3/field/{fieldId}/context/{contextId}/option")
    suspend fun createCustomFieldOption(
        @Body fieldId: String,
        @Body contextId: Long,
        @Body bulkCustomFieldOptionCreateRequest: BulkCustomFieldOptionCreateRequest
    ): CustomFieldCreatedContextOptionsList

    /**
     * GET /rest/api/3/customFieldOption/{id}
     *
     * Returns a custom field option. For example, an option in a select list.

    Note that this operation **only works for issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource**, it cannot be used with issue field select list options created by Connect apps.

    This operation can be accessed anonymously.

     **[Permissions](#permissions) required:** The custom field option is returned as follows:

     *  if the user has the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *  if the user has the *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for at least one project the custom field is used in, and the field is visible in at least one layout the user has permission to view.
     * @param id The ID of the custom field option.  (example: null)
     *
     * @return CustomFieldOption
     */
    @GET("/rest/api/3/customFieldOption/{id}")
    suspend fun getCustomFieldOption(
        @Body id: String
    ): CustomFieldOption

    /**
     * GET /rest/api/3/field/{fieldId}/context/{contextId}/option
     *
     * Returns a [paginated](#pagination) list of all custom field option for a context. Options are returned first then cascading options, in the order they display in Jira.

    This operation works for custom field options created in Jira or the operations from this resource. **To work with issue field select list options created for Connect apps use the [Issue custom field options (apps)](#api-group-issue-custom-field-options--apps-) operations.**

     **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * @param fieldId The ID of the custom field.  (example: null)
     * @param contextId The ID of the context.  (example: null)
     * @param optionId The ID of the option. (optional) (example: null)
     * @param onlyOptions Whether only options are returned. (optional) (example: null)
     * @param startAt The index of the first item to return in a page of results (page offset). (optional) (example: null)
     * @param maxResults The maximum number of items to return per page. (optional) (example: null)
     *
     * @return PageBeanCustomFieldContextOption
     */
    @GET("/rest/api/3/field/{fieldId}/context/{contextId}/option")
    suspend fun getOptionsForContext(
        @Body fieldId: String,
        @Body contextId: Long,
        @Query("optionId") optionId: Long? = null,
        @Query("onlyOptions") onlyOptions: Boolean = false,
        @Query("startAt") startAt: Long = 0,
        @Query("maxResults") maxResults: Int = 100
    ): PageBeanCustomFieldContextOption
}