/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.EntityProperty
import jira.api.models.PropertyKeys
import retrofit2.http.Body
import retrofit2.http.GET

interface IssueTypePropertiesApi {

    /**
     * GET /rest/api/3/issuetype/{issueTypeId}/properties/{propertyKey}
     *
     * Returns the key and value of the [issue type property](https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties).

    This operation can be accessed anonymously.

     **[Permissions](#permissions) required:**

     *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) to get the details of any issue type.
     *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) to get the details of any issue types associated with the projects the user has permission to browse.
     * @param issueTypeId The ID of the issue type.  (example: null)
     * @param propertyKey The key of the property. Use [Get issue type property keys](#api-rest-api-3-issuetype-issueTypeId-properties-get) to get a list of all issue type property keys.  (example: null)
     *
     * @return EntityProperty
     */
    @GET("/rest/api/3/issuetype/{issueTypeId}/properties/{propertyKey}")
    suspend fun getIssueTypeProperty(
        @Body issueTypeId: String,
        @Body propertyKey: String
    ): EntityProperty

    /**
     * GET /rest/api/3/issuetype/{issueTypeId}/properties
     *
     * Returns all the [issue type property](https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties) keys of the issue type.

    This operation can be accessed anonymously.

     **[Permissions](#permissions) required:**

     *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) to get the property keys of any issue type.
     *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) to get the property keys of any issue types associated with the projects the user has permission to browse.
     * @param issueTypeId The ID of the issue type.  (example: null)
     *
     * @return PropertyKeys
     */
    @GET("/rest/api/3/issuetype/{issueTypeId}/properties")
    suspend fun getIssueTypePropertyKeys(
        @Body issueTypeId: String
    ): PropertyKeys
}