/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.ApplicationProperty
import jira.api.models.Configuration
import retrofit2.http.GET
import retrofit2.http.Query

interface JiraSettingsApi {

    /**
     * GET /rest/api/3/application-properties/advanced-settings
     *
     * Returns the application properties that are accessible on the *Advanced Settings* page. To navigate to the *Advanced Settings* page in Jira, choose the Jira icon > **Jira settings** > **System**, **General Configuration** and then click **Advanced Settings** (in the upper right).

     **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @return List<ApplicationProperty>
     */
    @GET("/rest/api/3/application-properties/advanced-settings")
    suspend fun getAdvancedSettings(): List<ApplicationProperty>

    /**
     * GET /rest/api/3/application-properties
     *
     * Returns all application properties or an application property.

    If you specify a value for the `key` parameter, then an application property is returned as an object (not in an array). Otherwise, an array of all editable application properties is returned. See [Set application property](#api-rest-api-3-application-properties-id-put) for descriptions of editable properties.

     **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * @param key The key of the application property. (optional) (example: null)
     * @param permissionLevel The permission level of all items being returned in the list. (optional) (example: null)
     * @param keyFilter When a `key` isn't provided, this filters the list of results by the application property `key` using a regular expression. For example, using `jira.lf.*` will return all application properties with keys that start with *jira.lf.*. (optional) (example: null)
     *
     * @return List<ApplicationProperty>
     */
    @GET("/rest/api/3/application-properties")
    suspend fun getApplicationProperty(
        @Query("key") key: String? = null,
        @Query("permissionLevel") permissionLevel: String? = null,
        @Query("keyFilter") keyFilter: String? = null
    ): List<ApplicationProperty>

    /**
     * GET /rest/api/3/configuration
     *
     * Returns the [global settings](https://confluence.atlassian.com/x/qYXKM) in Jira. These settings determine whether optional features (for example, subtasks, time tracking, and others) are enabled. If time tracking is enabled, this operation also returns the time tracking configuration.

     **[Permissions](#permissions) required:** Permission to access Jira.
     *
     * @return Configuration
     */
    @GET("/rest/api/3/configuration")
    suspend fun getConfiguration(): Configuration
}