/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.License
import jira.api.models.LicenseMetric
import retrofit2.http.Body
import retrofit2.http.GET

interface LicenseMetricsApi {

    /**
     * GET /rest/api/3/license/approximateLicenseCount/product/{applicationKey}
     *
     * Returns the total approximate number of user accounts for a single Jira license. Note that this information is cached with a 7-day lifecycle and could be stale at the time of call.

     **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * @param applicationKey The ID of the application, represents a specific version of Jira.  (example: null)
     *
     * @return LicenseMetric
     */
    @GET("/rest/api/3/license/approximateLicenseCount/product/{applicationKey}")
    suspend fun getApproximateApplicationLicenseCount(
        @Body applicationKey: String
    ): LicenseMetric

    /**
     * GET /rest/api/3/license/approximateLicenseCount
     *
     * Returns the approximate number of user accounts across all Jira licenses. Note that this information is cached with a 7-day lifecycle and could be stale at the time of call.

     **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @return LicenseMetric
     */
    @GET("/rest/api/3/license/approximateLicenseCount")
    suspend fun getApproximateLicenseCount(): LicenseMetric

    /**
     * GET /rest/api/3/instance/license
     *
     * Returns licensing information about the Jira instance.

     **[Permissions](#permissions) required:** None.
     *
     * @return License
     */
    @GET("/rest/api/3/instance/license")
    suspend fun getLicense(): License
}