/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.EntityProperty
import jira.api.models.PropertyKeys
import retrofit2.http.Body
import retrofit2.http.GET

interface ProjectPropertiesApi {

    /**
     * GET /rest/api/3/project/{projectIdOrKey}/properties/{propertyKey}
     *
     * Returns the value of a [project property](https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties).

    This operation can be accessed anonymously.

     **[Permissions](#permissions) required:** *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the property.
     * @param projectIdOrKey The project ID or project key (case sensitive).  (example: null)
     * @param propertyKey The project property key. Use [Get project property keys](#api-rest-api-3-project-projectIdOrKey-properties-get) to get a list of all project property keys.  (example: null)
     *
     * @return EntityProperty
     */
    @GET("/rest/api/3/project/{projectIdOrKey}/properties/{propertyKey}")
    suspend fun getProjectProperty(
        @Body projectIdOrKey: String,
        @Body propertyKey: String
    ): EntityProperty

    /**
     * GET /rest/api/3/project/{projectIdOrKey}/properties
     *
     * Returns all [project property](https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties) keys for the project.

    This operation can be accessed anonymously.

     **[Permissions](#permissions) required:** *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
     * @param projectIdOrKey The project ID or project key (case sensitive).  (example: null)
     *
     * @return PropertyKeys
     */
    @GET("/rest/api/3/project/{projectIdOrKey}/properties")
    suspend fun getProjectPropertyKeys(
        @Body projectIdOrKey: String
    ): PropertyKeys
}