/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.ContainerForProjectFeatures
import retrofit2.http.Body
import retrofit2.http.GET

interface ProjectFeaturesApi {

    /**
     * GET /rest/api/3/project/{projectIdOrKey}/features
     *
     * Returns the list of features for a project.
     * @param projectIdOrKey The ID or (case-sensitive) key of the project.  (example: null)
     *
     * @return ContainerForProjectFeatures
     */
    @GET("/rest/api/3/project/{projectIdOrKey}/features")
    suspend fun getFeaturesForProject(
        @Body projectIdOrKey: String
    ): ContainerForProjectFeatures
}