/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.ServerInformation
import retrofit2.http.GET

interface ServerInfoApi {

    /**
     * GET /rest/api/3/serverInfo
     *
     * Returns information about the Jira instance.

    This operation can be accessed anonymously.

     **[Permissions](#permissions) required:** None.
     *
     * @return ServerInformation
     */
    @GET("/rest/api/3/serverInfo")
    suspend fun getServerInfo(): ServerInformation
}