/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.TimeTrackingConfiguration
import jira.api.models.TimeTrackingProvider
import retrofit2.http.GET

interface TimeTrackingApi {

    /**
     * GET /rest/api/3/configuration/timetracking/list
     *
     * Returns all time tracking providers. By default, Jira only has one time tracking provider: *JIRA provided time tracking*. However, you can install other time tracking providers via apps from the Atlassian Marketplace. For more information on time tracking providers, see the documentation for the [ Time Tracking Provider](https://developer.atlassian.com/cloud/jira/platform/modules/time-tracking-provider/) module.

     **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @return List<TimeTrackingProvider>
     */
    @GET("/rest/api/3/configuration/timetracking/list")
    suspend fun getAvailableTimeTrackingImplementations(): List<TimeTrackingProvider>

    /**
     * GET /rest/api/3/configuration/timetracking
     *
     * Returns the time tracking provider that is currently selected. Note that if time tracking is disabled, then a successful but empty response is returned.

     **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @return TimeTrackingProvider
     */
    @GET("/rest/api/3/configuration/timetracking")
    suspend fun getSelectedTimeTrackingImplementation(): TimeTrackingProvider

    /**
     * GET /rest/api/3/configuration/timetracking/options
     *
     * Returns the time tracking settings. This includes settings such as the time format, default time unit, and others. For more information, see [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).

     **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @return TimeTrackingConfiguration
     */
    @GET("/rest/api/3/configuration/timetracking/options")
    suspend fun getSharedTimeTrackingConfiguration(): TimeTrackingConfiguration
}