/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.CreateUiModificationDetails
import jira.api.models.PageBeanUiModificationDetails
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.Query

interface UIModificationsAppsApi {

    /**
     * POST /rest/api/3/uiModifications
     *
     * Creates a UI modification. UI modification can only be created by Forge apps.

    Each app can define up to 3000 UI modifications. Each UI modification can define up to 1000 contexts. The same context can be assigned to maximum 100 UI modifications.

     **[Permissions](#permissions) required:**

     *  *None* if the UI modification is created without contexts.
     *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for one or more projects, if the UI modification is created with contexts.

    The new `write:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
     * @param createUiModificationDetails, request body
     *
     * @return Unit
     */
    @POST("/rest/api/3/uiModifications")
    suspend fun createUiModification(
        @Body createUiModificationDetails: CreateUiModificationDetails
    ): Unit

    /**
     * GET /rest/api/3/uiModifications
     *
     * Gets UI modifications. UI modifications can only be retrieved by Forge apps.

     **[Permissions](#permissions) required:** None.

    The new `read:app-data:jira` OAuth scope is 100% optional now, and not using it won't break your app. However, we recommend adding it to your app's scope list because we will eventually make it mandatory.
     * @param startAt The index of the first item to return in a page of results (page offset). (optional) (example: null)
     * @param maxResults The maximum number of items to return per page. (optional) (example: null)
     * @param expand Use expand to include additional information in the response. This parameter accepts a comma-separated list. Expand options include:

     *  `data` Returns UI modification data.
     *  `contexts` Returns UI modification contexts. (optional) (example: null)
     *
     * @return PageBeanUiModificationDetails
     */
    @GET("/rest/api/3/uiModifications")
    suspend fun getUiModifications(
        @Query("startAt") startAt: Long = 0,
        @Query("maxResults") maxResults: Int = 50,
        @Query("expand") expand: String? = null
    ): PageBeanUiModificationDetails
}