/**
 * ⚠️ Do not edit manually ⚠️
 * Generated by openapi-generate. See project's `openapi-generate.sh` for details
 */
package jira.api.apis

import jira.api.models.StatusDetails
import retrofit2.http.Body
import retrofit2.http.GET

interface WorkflowStatusesApi {

    /**
     * GET /rest/api/3/status/{idOrName}
     *
     * Returns a status. The status must be associated with an active workflow to be returned.

    If a name is used on more than one status, only the status found first is returned. Therefore, identifying the status by its ID may be preferable.

    This operation can be accessed anonymously.

    [Permissions](#permissions) required: None.
     * @param idOrName The ID or name of the status.  (example: null)
     *
     * @return StatusDetails
     */
    @GET("/rest/api/3/status/{idOrName}")
    suspend fun getStatus(
        @Body idOrName: String
    ): StatusDetails

    /**
     * GET /rest/api/3/status
     *
     * Returns a list of all statuses associated with active workflows.

    This operation can be accessed anonymously.

     **[Permissions](#permissions) required:** None.
     *
     * @return List<StatusDetails>
     */
    @GET("/rest/api/3/status")
    suspend fun getStatuses(): List<StatusDetails>
}